### ISSUE TITLE
BUG: Auto split window if it's nvim's terminal one

### ISSUE THREAD

**Issue by tmpm697** [nvim-neo-tree/neo-tree.nvim#1064]
### Did you check docs and existing issues?

- [X] I have read all the docs.
- [X] I have searched the existing issues.
- [X] I have searched the existing discussions.

### Neovim Version (nvim -v)

v0.10.0-dev-684+g80cf0f3d2

### Operating System / Version

Archlinux

### Describe the Bug

while `:term` and then put it into normal mode by `<C-\><C-n>` then select other file from neo-tree tree, the new buffer will be split to another window

this is not happen if open new buffer from normal file buffer.

### Steps to Reproduce

1. nvim
2. select some files from neo-tree window
3. start terminal `:term`
4. press `<c-\><c-n>` to put nvim's terminal to normal mode
5. select another buffer from neo-tree window
6. observe that new buffer is split to new window --> now there's three window: 1 for neo-tree, 1 for nvim's terminal and 1 for new buffer

### Expected Behavior

There's only two buffer after select new one from neo-tree: 1 for neo-tree, 1 for new buffer

### Your Configuration

```Lua
return {
	"nvim-neo-tree/neo-tree.nvim",
	branch = "main",
	cmd = "Neotree",
	dependencies = {
		"nvim-lua/plenary.nvim",
		"nvim-tree/nvim-web-devicons", -- not strictly required, but recommended
		"MunifTanjim/nui.nvim",
	},
}
```

**Comment by nhat-vo** [comment]
You can set `config.open_files_do_not_replace_types` to remove the `"terminal"` value. https://github.com/nvim-neo-tree/neo-tree.nvim/blob/293395c80224fd6f179dffc1c641430c85f999b0/lua/neo-tree/defaults.lua#L39

The behavior you saw is because when opening a new file, neo-tree will avoid replacing the terminal buffer. Since there is no other window left, it splits into a new window. In most cases, users would want neo-tree to avoid the terminal window, so I do not think that this is a bug. Does this answer your question?
