### ISSUE TITLE
Error in neo-tree.utils.debounce

### ISSUE THREAD

**Issue by meanindra** [nvim-neo-tree/neo-tree.nvim#108]
![Screenshot from 2022-02-01 22-45-32](https://user-images.githubusercontent.com/36324543/152018500-e7147c3c-a766-4d5a-80e7-1cf0b5757b15.png)
Every time I am getting this error when I use any command example `:NeoTreeReveal`

**Comment by cseickel** [comment]
My best guess is that either there is a file or directory with newlines in the name, or you have created a custom component that uses newlines. Can you check on that? Maybe try to `cd` into another directory and run `NeoTreeShow` from there?

If it is not a filename issue, can you post your config so I can see if it is a specific mix of options that cause it?

**Comment by meanindra** [comment]
> Maybe try to cd into another directory and run NeoTreeShow from there?

It is not wrking. same error
![image](https://user-images.githubusercontent.com/36324543/152022060-20064f5a-8c7c-4c80-a869-511bb20f105e.png)

> If it is not a filename issue, can you post your config so I can see if it is a specific mix of options that cause it?

https://gist.github.com/meanindra/bc7c58f09c22e3557c930d65fd1fac63

**Comment by cseickel** [comment]
@meanindra, can you try out main and tell me if it fixes your error?

**Comment by meanindra** [comment]
Previous error is fixed but new new error showing `Invalid mapping for bd : nil`

![image](https://user-images.githubusercontent.com/36324543/152094344-ce1a068d-4968-4684-b65e-c38459aa6beb.png)

**Comment by cseickel** [comment]
I noticed the `bd` mapping in your config, it's because you have mapped `bd` to the `buffer_delete` command in the filesystem, but that command is not supported in that source. It is a command that is unique to the `buffers` source. You just need to delete that line.

> Edit: I don't know what I did but this error also not showing.
If you are referring to the diagnostic error, it is showing as a red E next to the file in the tree. See `:h neo-tree-diagnostics` for more info.
