### ISSUE TITLE
BUG: `show` moves cursor to Neotree window when `source="last"`

### ISSUE THREAD

**Issue by speelbarrow** [nvim-neo-tree/neo-tree.nvim#1151]
### Did you check docs and existing issues?

- [X] I have read all the docs.
- [X] I have searched the existing issues.
- [X] I have searched the existing discussions.

### Neovim Version (nvim -v)

0.9.2

### Operating System / Version

macOS 14.0

### Describe the Bug

When calling `:Neotree show source=last`, I expect the Neotree window to open but for the cursor to remain where it is. However, if the Neotree window is not open and the previously displayed source (i.e. `last`) was not the `filesystem` source, the cursor moves to the Neotree window.

### Screenshots, Traceback

https://github.com/nvim-neo-tree/neo-tree.nvim/assets/44714422/0eff45a6-2117-4f66-bde5-60c65bc535c3

*NOTE*: While creating this screen recording, I discovered that `:Neotree action=focus source=<any>` leaves the cursor outside the Neotree window.

### Steps to Reproduce

1. Open Neotree
2. Switch to a source other than `filesystem`
3. Close Neotree
4. Run `:Neotree show source=last`

### Expected Behavior

Expected the Neotree window to open but for my cursor to remain in the file window.

### Your Configuration

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
}

local neotree_config = {
  "nvim-neo-tree/neo-tree.nvim",
  dependencies = { "MunifTanjim/nui.nvim", "nvim-tree/nvim-web-devicons", "nvim-lua/plenary.nvim" },
  cmd = { "Neotree" },
  keys = {  },
  opts = {  },
}

table.insert(plugins, neotree_config)
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
```

**Comment by pysan3** [comment]
This should in fact be reproducible not only with `:Neotree show source=last` but with `:Neotree show source=buffers` or any other source other than `filesystem`.

This is due to `navigate` function not having enough arguments compared to `filesystem.navigate` (especially calling `callback` in this case).

- filesystem
https://github.com/nvim-neo-tree/neo-tree.nvim/blob/63ebe879ad4798b66d29c0b2c8d04942389d438e/lua/neo-tree/sources/filesystem/init.lua#L172
- buffers
https://github.com/nvim-neo-tree/neo-tree.nvim/blob/63ebe879ad4798b66d29c0b2c8d04942389d438e/lua/neo-tree/sources/buffers/init.lua#L85
- git_status
https://github.com/nvim-neo-tree/neo-tree.nvim/blob/63ebe879ad4798b66d29c0b2c8d04942389d438e/lua/neo-tree/sources/git_status/init.lua#L26
- document_symbols
https://github.com/nvim-neo-tree/neo-tree.nvim/blob/63ebe879ad4798b66d29c0b2c8d04942389d438e/lua/neo-tree/sources/document_symbols/init.lua#L62

I thought they all should accept the exact same amount of arguments since they are all called from 
https://github.com/nvim-neo-tree/neo-tree.nvim/blob/63ebe879ad4798b66d29c0b2c8d04942389d438e/lua/neo-tree/sources/manager.lua#L484-L488

Do you know any reason why they don't have the same interfaces? @cseickel

**Comment by cseickel** [comment]
> Do you know any reason why they don't have the same interfaces? @cseickel

Because the `filesystem` source is much more complicated and more frequently used so it continued to evolve after the other sources stopped changing. This is an oversight. The correct thing to do here is to add the callback argument to all sources.
