### ISSUE TITLE
FEATURE:  Max width in window?

### ISSUE THREAD

**Issue by vinoff** [nvim-neo-tree/neo-tree.nvim#1250]
Sometimes, when I open/close other windows, Neo-Tree gets redrawn with a larger width than the one I have configured. Is there an option to have a max-width, so that Neo-tree is never bigger than that value?

**Comment by vinoff** [comment]
I do have auto_expand_width = false. Here is a way to reproduce:

- Open Nvim and Neo-Tree (Neo-Tree is to the left of the other Nvim Window)
- Open something to the left of Neo Tree (in my  case, I opened some nvim-dap windows)
- Close whatever was to the left of Neo Tree (in my case, I closed the nvim-dap-ui windows)
- Neo-Tree will take that space.

**Comment by cseickel** [comment]
I'm afraid that's just how window management in (neo)vim works, neo-tree has no control over that.

My first suggestion is to not open another sidebar to the left of an existing sidebar. Why not use the right hand side for one of them or create a mapping that will always close one before opening the other?

Beyond that, you may want to check out [edgy.nvim](https://github.com/folke/edgy.nvim) for more advanced IDE like layout management.

**Comment by axelhj** [comment]
I'm having this issue constantly since a few weeks. Whenever I use splits and equalize the widths using `<C-w>=` neo-tree stays my preferred size. Whenever I toggle nvim-dap-ui, its size is affected and it grows successively until I open + close it. I am not sure that it happened initially when I started using nvim-dap-ui along with neo-tree.

I just wanted to know if there is some autocommand that could observe the neo-tree width and reset the size it if changed. Then I could put that in my config? It seems to do something similar whenever I manually equalize my split windows.
