### ISSUE TITLE
breaking change at 0c5081a (support netrw)

### ISSUE THREAD

**Issue by BerkeleyTrue** [nvim-neo-tree/neo-tree.nvim#132]
I have a custom function that will toggle a folder open using space bar: When it opens a folder, it enters the folder `feedkes 'j'`. If it's on a file or on an open folder, it closes that folder. 

(warning: fennel ahead)
```fnl
            (fn toggle-directory [state]
              (let [tree (. state :tree)
                    node (tree:get_node)
                    is-dir (= :directory (. node :type))
                    is-open (when is-dir (: node :is_expanded))]
                (if is-dir
                  (do
                    (fs.toggle_directory node)
                    (when-not is-open (keys.feed :j)))
                  (cc.close_node state))))
```

Before commit 0c5081a, this function worked fine. 

~~After that commit, I keep getting tree (`tree = state:tree()`) as undefined, which breaks on the next line where I get the node (`node = tree:get_node`). Specifically, when my cursor is on a closed directory. It works fine on a file or open directory.~~

Actually, the API for fs.toggle_directory changed. I now need to append state to fs.toggle_directory ~~(`fs.toggle_directory(node state)`)~~ edit: (`fs.toggle_directory(state, node)`)

Is there a better way to do this were I'm not relying on internal workings that might change often? I can work around this but I don't want to keep fidgeting this function.

Thanks for the help.

**Comment by cseickel** [comment]
First off, I apologize for the breaking change. I had not thought about this as a function that people would use but I see why it's needed for custom functions. In the future, I'll consider **any** exported function signatures the public api and create a new major version if I need to change them.

I don't really see a better way to have handled this other than rewriting the needed functionality of toggle_directory in your own function. I also don't think there will be another significant change to this api.

**The final answer is: "I won't do it again!"**

BTW - the order of parameters is actually: `state, node` instead of `node, state`

**Comment by cseickel** [comment]
Yeah, maybe you're right about that. Maybe just prefixing private methods with an underscore is a clear way of denoting it as private. I'll give this a little more thought and post a policy on the README.
