### ISSUE TITLE
FEATURE: Put cursor in the beginning of line in normal mode

### ISSUE THREAD

**Issue by luthfielaroeha** [nvim-neo-tree/neo-tree.nvim#1371]
### Did you check the docs?

- [X] I have read all the docs.

### Is your feature request related to a problem? Please describe.

Most of the time, when renaming a file I just want to rename the filename without changing the extension. Currently the cursor placed in the end of line.

### Describe the solution you'd like.

I think it would be better to put the cursor in the beginning of the line so we can just use `cw` or `ct.` to change the filename.

**Comment by pysan3** [comment]
https://github.com/nvim-neo-tree/neo-tree.nvim/issues/602

**Comment by luthfielaroeha** [comment]
Sorry probably I'm missing something.
I'm aware that the normal mode exists, but when I want to rename the file, the cursor started in the end of the line.
Is there any other config to make the cursor in the beginning of the line instead?

<img width="261" alt="image" src="https://github.com/nvim-neo-tree/neo-tree.nvim/assets/11254971/4ce2d962-4d43-4b5e-9f6b-1615e632f995">

**Comment by pysan3** [comment]
Oh I'm sorry.

**Comment by bwpge** [comment]
Just adding info for anyone looking to pick this up: you might have success getting the `nui` input/popup window ID ([`split.winid`](https://github.com/MunifTanjim/nui.nvim/tree/main/lua/nui/popup#popup)) and setting the cursor with [`vim.api.nvim_win_set_cursor()`](https://neovim.io/doc/user/api.html#nvim_win_set_cursor()).

**Comment by pysan3** [comment]
`neo_tree_popup_input_ready` event has been added with https://github.com/nvim-neo-tree/neo-tree.nvim/pull/1372.

Please read `:h neo-tree-events` for more information.

**Comment by uthmanmoh** [comment]
Not sure if this is the right place to ask this, but does anyone know if there's a way to control what happens based on the different input popups?
I want to be able to customize what happens when the input box for the `move` operation opens, and a different action when the input box for `add` opens

**Comment by uthmanmoh** [comment]
Also with this new suggested event:
```lua
{
  event = "neo_tree_popup_input_ready",
  ---@param input NuiInput
  handler = function(input)
    vim.cmd("stopinsert") -- Enter normal mode
  end,
}
```
I am unable to enter normal mode after manually entering insert mode with `i`, since pressing esc even in insert mode just closes the input. Is there a way to make it so that I need to press `esc` from within normal mode only to exit the input box, as I believe it used to be before?

**Comment by cseickel** [comment]
> Not sure if this is the right place to ask this, but does anyone know if there's a way to control what happens based on the different input popups? I want to be able to customize what happens when the input box for the `move` operation opens, and a different action when the input box for `add` opens

There's no simple way to do this, but it would be a nice feature. Someone could probably come up with a code snippet to inspect the title displayed in the wrapper window.

> I am unable to enter normal mode after manually entering insert mode with i, since pressing esc even in insert mode just closes the input.

That's a bug, or at least an oversight. I made a separate issue out of that.

**Comment by pysan3** [comment]
Isn't it just up to the user to remap using `input.map` inside the event by themselves if they want this feature?

**Comment by cseickel** [comment]
> Isn't it just up to the user to remap using `input:map` inside the event by themselves if they want this feature?

Maybe, but we make the mapping with Nui so I'm not sure how easy it is to unmap from the event.

**Comment by pysan3** [comment]
Wdym? There's `input:unmap` or do you mean something else?

**Comment by cseickel** [comment]
> Wdym? There's `input:unmap` or do you mean something else?

`input` is a Nui object that is not available in the event and also not standard nvim api so I'm not sure its the best user experience even if we could provide a reference to that object.

**Comment by pysan3** [comment]
I'm sorry, I even put it in the docs but forgot to pass `input` as an argument to `fire_event`. This is more of a bug I'd say.

I think we should pass it as either `input` or `{ input = input }`. 

Which one would you prefer? I'll make a PR later today.

**Comment by pysan3** [comment]
@uthmanmoh 

I've created https://github.com/nvim-neo-tree/neo-tree.nvim/pull/1398. Do you think this method works for you?

**Comment by uthmanmoh** [comment]
Yup being able to control the mappings seems good. Thanks for the fix.

Although im thinking now with the complexity of this event handler increasing, it might have been a good idea to keep the boolean option for enabling normal mode which if set to 'true' would just create this handler. That makes sense as its own option since thats a basic functionality imo.

Let me know if this makes sense, maybe I can create a separate ticket for it

**Comment by pysan3** [comment]
This is my opinion on that https://github.com/nvim-neo-tree/neo-tree.nvim/pull/1372#issuecomment-1975233977

I understand that it is complicated but I've seen many FR that are slightly different for everybody (normal by default, put cursor before extension but in insert mode, put cursor in front, ...) and it is hard to distinguish where we officially support and not. 

Therefore imo I think it's better to say that we support one and only one feature (insert + maps for `<esc>, q`) and everyone that don't like this behavior, they can edit whatever they want. 
If we go this route, users can share their handler in the wiki and everybody who copy that code will work because everybody is on the same starting point, regardless of any other config option.

**Comment by uthmanmoh** [comment]
That sounds alright to me. Thanks for clarifying
