### ISSUE TITLE
Autoclosing option opening a file? 

### ISSUE THREAD

**Issue by korsmakolnikov** [nvim-neo-tree/neo-tree.nvim#176]
There is a way or could we have an option like in the original NerdTree such as when a file is opened Neo-Tree will close itself? 

Thank you

**Comment by cseickel** [comment]
Yes there is, here is how you do that: https://github.com/nvim-neo-tree/neo-tree.nvim/wiki/Recipes#auto-close-on-open-file

**Comment by Mickychen00** [comment]
Hi! I used "Neotree focus toggle" command to open a Neotree window and selected a file with "t (tabnew)" to open it in a new tab. Despite I use the configuration from https://github.com/nvim-neo-tree/neo-tree.nvim/wiki/Recipes#auto-close-on-open-file, I found the original Neotree window is still not closed.
Is there any wrong action?

**Comment by cseickel** [comment]
@Mickychen00 That recipe will only close Neo-tree windows within the current tab. I'm not sure off the top of my head how to make that work with the "open in new tab" command.

I have always thought that recipe was silly though. If you don't want Neo-tree to stay open after selecting a file, you should be using the `float` position instead of a sidebar.
