### ISSUE TITLE
Dynamic resizing

### ISSUE THREAD

**Issue by ziombo** [nvim-neo-tree/neo-tree.nvim#177]
Is it possible to set neo-tree window's width on runtime?  Sometimes the project I'm working on has nested files and it would help me if I was able to resize the window. Something similar to NvimTreeResize in https://github.com/kyazdani42/nvim-tree.lua.

**Comment by cseickel** [comment]
What does NvimTreeResize do exactly? Is it an auto resize to fit the content, or does it set the size to a specified value as an argument to the command?

**Comment by ziombo** [comment]
It set's size to a specific value. I use it like this: 
![image](https://user-images.githubusercontent.com/15613606/157980000-7af75955-8f5a-4967-aaaa-8d4990739484.png)

Not the pretties solution, but allows me to quickly adjust the width to my needs

**Comment by cseickel** [comment]
Assuming that you always have your tree as a left hand sidebar, you can do that with native vim commands:

```
:vertical 1resize +15
:vertical 1resize -15
```

If neo-tree is not always window 1 for you, I can probably give you a slightly more complicated mapping to identify what window it is and resize that. I don't think it's worth having a special NeoTree command though, since the functionality is already handled natively.

Now, if what you really want is to tell Neo-tree to resize itself to fit the widest folder or file name, then that's something that would require a custom Neo-tree command.


You might also be interested in my own resize mapping, which applies to any window and adjusts the amount of resize according to how big the window currently is:
https://github.com/cseickel/dotfiles/blob/787591f46afa441607adf727ae382644e16f695b/config/nvim/core-mappings.vim#L165
