### ISSUE TITLE
Getting lag with `use_libuv_file_watcher = true`

### ISSUE THREAD

**Issue by lopi-py** [nvim-neo-tree/neo-tree.nvim#188]
https://gyazo.com/01916d52f16e0577554743685f055a64 (the cursor flashes and goes to the last previous position when doing the flash and my neovim feels a bit slower)
maybe it's because I'm on Windows but I'm not sure, also when I exit from neovim with the tree opened, I get this
```[neo-tree.nvim] [ERROR 18:04:17] ...packerstart^@eo-tree.nvim/lua/neo-tree/events/queue.lua:144: Error in event handler for event git_status_changed[filesystem.git_status_changed]: ...tasitepackpackerstart^@ui.nvim/lua/nui/tree/init.lua:365: Vim:E322: line number out of range: 1 past the end```

**Comment by cseickel** [comment]
Maybe it shouldn't be turned on by default after all. That is the behavior I see in a `.git` directory which is why I explicitly turn it off in those dirs, but I don't see why it should happen in that dir. It could be that it just isn't usable on Windows.

For now I think I'll just revert the default value to false.

**Comment by lucasyarza** [comment]
Any way to fix this apart from disabling the option?

**Comment by cseickel** [comment]
@lucasyarza  Not that I know of. I don't develop on Windows so I can't really investigate the issue. Someone else would have to work on the issue for it to get fixed.

**Comment by lopi-py** [comment]
I think this is a `libuv` problem that is not working on Windows but I'm not sure

**Comment by lopi-py** [comment]
@lucasyarza I tried now and I haven't lag, so I guess it was a neo-tree problem, but as I said, now I'm not getting lag and works fine

**Comment by cseickel** [comment]
@lopi-py The issue before was that libuv was throwing file changed events constantly. It's possible we've just sped up neo-tree enough that it can handle constant refreshes without slowing things down. I would check the logs and Task Manager just to be sure that it's really fixed.

**Comment by lopi-py** [comment]
> @lopi-py The issue before was that libuv was throwing file changed events constantly. It's possible we've just sped up neo-tree enough that it can handle constant refreshes without slowing things down. I would check the logs and Task Manager just to be sure that it's really fixed.

The cpu usage goes to 3% but when I refresh manually it goes to 2.5% so I think it's ok, also the logs seems all fine

**Comment by nyngwang** [comment]
> [...] It's possible we've just sped up neo-tree enough that it can handle constant refreshes [...]

@cseickel: Does this mean that I can turn it off since this option was to speed up neo-tree while now it's fast enough without it? (if I'm using macOS.)

**Comment by nyngwang** [comment]
> @lopi-py: The cpu usage goes to 3% [...]

FYI: I use CPU usage as the most important criteria to decide whether I should keep a plugin or not. So must keep it low. it's one of the biggest advantages of NeoVim against modern IDE.

**Comment by cseickel** [comment]
@nyngwang 
> Does this mean that I can turn it off since this option was to speed up neo-tree while now it's fast enough without it? (if I'm using macOS.)

That's kind of backwards. This thread was about the `use_libuv_file_watcher` causing performance issues. I don't think having it on was ever meant as a way to improve performance. At best it would have no impact, but if there is an impact it would be most likely be negative rather than a performance boot.

The purpose of using the watcher is avoid having to manually refresh when files are changing outside of neovim buffers. I also think it's less buggy than vim events because other plugins can introduce complications with that system. The issue for some people is that it slowed everything down because it was throwing too many "file changed" events for some reason.

If you had problems with having the `use_libuv_file_watcher` option turned on before, it sounds like you can give it another try and see if it works better for you now. If you did not have any issues before, I would leave it on.

**Comment by nyngwang** [comment]
@cseickel: I'm still keeping this option on :) OK, but there is a problem I have experienced for two months(or more?) I'm using a plugin I made for myself to change the current working directory. It seems that the tree would not update when this option is on and the current directory did change. Maybe I should open an issue of it though.

**Comment by cseickel** [comment]
@nyngwang The cwd issue is not related to the file watcher at all. I'll create a new issue for that.
