### ISSUE TITLE
Search <CR> stuffs up buffers

### ISSUE THREAD

**Issue by axieax** [nvim-neo-tree/neo-tree.nvim#219]
Selecting a file to open using <CR> in search mode (/) stuffs up the buffers for some reason, but opens fine normally without search. Similar behaviour can be seen by selecting other entries that appear in a search.

Open behaviour is fixed once the search prompt is gone (e.g. switching back to the menu).

https://user-images.githubusercontent.com/62098008/160389259-68b6786d-a1ea-4e6c-a7bd-989bbb1f5095.mp4

**Comment by cseickel** [comment]
By "stuffs up the buffer", do you mean "does not reset the search?" 

That behavior worked well for me because I always go back to it via a mapping which refreshes every time. The problem is that because the reset search refreshes, and that refresh is async, it will return with screen updates after the window has closed, which reactivates it. Leaving it alone when it goes into the background worked well for my usage but not for how you use it.

I'll need to update it to reset the search properly, in teh background, for the "current" position.

**Comment by axieax** [comment]
Hi sorry, I'm not too sure how to describe the buffer behaviour. I'm basically trying to describe the bufferline behaviour when opening a file after search ("inactive").
