### ISSUE TITLE
close_if_last_window quits neovim even if there are more than 1 open buffers.

### ISSUE THREAD

**Issue by AndreaHasani** [nvim-neo-tree/neo-tree.nvim#241]
It seems that setting close_if_last_window to true quits neovim even if there are still open buffers. I navigate neovim via buffers (not tabs) and it would be great if this feature switched to another buffer if there's still one left.

To simulate this issue, open two buffers and open neo-tree in one of them. When closing the buffer, neo-tree quite neovim.

I think one way to fix this would be to have neo-vim open as a float and try to position it left. I think I have seen some other plugins which do this. It works like a menu slider from left on apps (in this case it will be toggleable open and closed).

**Comment by cseickel** [comment]
It is explicitly a "close if last window". If you want neotree to stay open when it's the only window, but close if it's the only buffer, then that's an entirely different feature.

If it were open as a float and you tried to do something that closed the last window, you would actually get an error from nvim, so that won't help.

It sounds to me that what you actually want is to have nvim switch to the most recently used buffer when you delete the one that is active in a window, instead of closing the window. If that's correct, there is a plugin for that: https://github.com/famiu/bufdelete.nvim
