### ISSUE TITLE
Buffers view should show unloaded buffers as well

### ISSUE THREAD

**Issue by ur4ltz** [nvim-neo-tree/neo-tree.nvim#25]
The plugin does not display open buffers after starting a session.

![2022-01-09_13_37_19](https://user-images.githubusercontent.com/920202/148687590-45de947b-5dfc-4492-9efb-0403bda9fee1.png)

NeoTree buffers. (Left) 
Telescope buffers. (Front float)
 
Open nvim session, run any this command 
(
:NeoTreeShow buffers
:NeoTreeFocus buffers
:NeoTreeFloat buffers
)
only 1 buffer.

Run
:Telescope buffers

you can see that there are many more buffers.

**Comment by cseickel** [comment]
I see what the issue is. I am only showing **loaded** buffers in this list, while Telescope is including all listed buffers. I think that whether or not to show unloaded buffers should be a configuration option. I'll put this in as an enhancement and work on it soon.

I am going to make the current behavior the default and let you opt-in to showing unloaded buffers as well.

**Comment by ur4ltz** [comment]
Thanks!
