### ISSUE TITLE
Cut and Copy should work with Visual selection

### ISSUE THREAD

**Issue by cseickel** [nvim-neo-tree/neo-tree.nvim#253]
Right now you have to execute "copy_to_clipboard" and "cut_to_clipboard" operations on each node you want to cut/copy. It would be more natural to use native vim Visual mode selections and copy/cut everything in the selection when those commands are executed.

**Comment by lopi-py** [comment]
I think that allowing motions would be useful as well

**Comment by nyngwang** [comment]
@cseickel:

Hi, I must put an emphasis here that this feature should not be enabled by default.

I once accidentally "typing inside" neo-tree window(floating or not), because I accidentally touched the touch-pad of my laptop so the cursor was moved into it. If these kinds of shortcuts are enabled by default, then one might accidentally delete tons of files under the current working directory! Instead, providing hints for users interested in these behaviors and requiring them to **explicitly** add them into the config.

**Comment by cseickel** [comment]
This was just merged to `main` and will go out in the next release, which will probably happen tomorrow.

Note that motions are NOT supported in this feature, just visual mode selections.
