### ISSUE TITLE
Use relative/full path instead of just file name

### ISSUE THREAD

**Issue by axieax** [nvim-neo-tree/neo-tree.nvim#269]
As a feature I'm used to coming from NvimTree, I often find it difficult to see exactly which directory I'm adding a file to (especially since it depends on whether my cursor is on a directory or a file). Is it possible to do something like below for the default prompt, where the "default" text can also be edited, to quickly add a file to a parent directory for example?

NvimTree:

![image](https://user-images.githubusercontent.com/62098008/162971553-269f128e-04da-4695-b30c-cf984ceceecf.png)

neo-tree:

![image](https://user-images.githubusercontent.com/62098008/162972144-95e131bd-3618-4a8e-b147-788007134ece.png)

**Comment by cseickel** [comment]
Sounds like a good idea. The question is: What happens if you edit that path so that the new file or directory is outside of the current working directory? If the new file is inside of the current directory, it will refresh and reveal that file in the tree. If it isn't, should we:

1. Just not be allow the action, make the root dir part of the prompt that is not editable.
2. Automatically re-root to make the new file/dir visible
3. Prompt you to change working directory or not
4. Do nothing other then echoing a success message

**Comment by axieax** [comment]
Oo those are some great points! I reckon everyone's gonna have their own preferences regarding this behaviour so it might be great to expose a config option for this `creation-change-dir` behaviour or something. Not sure if it's possible to distinguish between a complete working directory change (i.e. `cd`) and just changing the directory displayed (without affecting the current working directory).

Personally, I would prefer the directory view to be updated (so I can open the file if necessary), but my current working directory (controlled by a rooter plugin such as [project.nvim](https://github.com/ahmedkhalf/project.nvim)) will be left as is. Not sure if you remember from my previous issues, but this is why I wanted specific behaviour when opening Neovim to a directory to display that directory, whilst my main neo-tree sidebar respects the cwd from the rooter plugin.

**Comment by cseickel** [comment]
I actually did this a few days ago in the `use-full-path-in-create-new` branch but I haven't merged it because I don't think I like it. It seems confusing to have all of that extra text in my prompt.

I think I'll try some more options here. I'm thinking of making the path relative to the current working directory to make the path shorter, and a different highlight for the path as long as it is unedited.

**Comment by axieax** [comment]
Hmm maybe it would be nice for a user to select whether they want `absolute`, `relative` or no path in `input` display. Having a test with your branch, the absolute path makes sense for me since I use `use_popups_for_input = false`, but this is too chonky for popups.

**Comment by cseickel** [comment]
I've adjusted the back-end code so that it can be configurable. The question now is what to name that option? Is this intuitive?

```
require("neo-tree").setup({
  include_path_in_add_command_prompt = "none" -- or "absolute" or "relative_to_root"
})
```

I can also just make separate commands for each variation:
```
require("neo-tree").setup({
  window = {
    mappings = [
      ["a"] = "add",
      --["a"] = "add_with_full_path",
      --["a"] = "add_with_relative_path",
    ]
  }
})
```

The latest version in this branch is using the relative path right now, but I think I'll go back to no path as the default. BTW - That branch was force pushed so you'll need to reset if you are just cloning the repo manually.

**Comment by axieax** [comment]
Love the changes!! 😍😍
Perhaps something like `add_path_format` is a bit simpler.

**Comment by cseickel** [comment]
I just had another idea... Instead of adding all these different variations on builtin commands, and all of these separate config options that might affect commands, I should just add configuration directly to the mapping declarations, like so:

```lua
require("neo-tree").setup({
  window = {
    mappings = [
      -- simple version still works and uses default config: 
      -- ["a"] = "add", 
      -- or optionally use a more verbose syntax that adds config options:
      ["a"] = { "add", show_path = "none" },
      -- ["a"] = { "add", show_path = "relative" }
      -- ["a"] = { "add", show_path = "full" }
    ]
  }
})
```

**Comment by axieax** [comment]
That's actually a brilliant idea!! Will you use "full" instead of "absolute" though?

**Comment by cseickel** [comment]
> That's actually a brilliant idea!! 
I'll go ahead and do that then. I don't think it should be all that complicated.


> Will you use "full" instead of "absolute" though?
I'm not married to it. If you think `absolute` is more obvious I'll go with that.

**Comment by axieax** [comment]
Ahh ok. I reckon `absolute` path makes more sense conventionally than `full` path, especially with `relative` path as an options.

**Comment by cseickel** [comment]
This has been added and the branch has been merged to `main`. I actually forgot that I already supported the table syntax for `mapping-options`, so I added a special `config` key to that syntax.

You can now specify your desired config like this:

```lua
    require("neo-tree").setup({
      window = {
        mappings = {
          ["a"] = {
            "add",
            nowait = true
            config = {
              show_path = "none" -- "none", "relative", "absolute"
            }
          },
        }
      }
    })

```

**Comment by axieax** [comment]
Thanks again for the amazing feature!
