### ISSUE TITLE
Rename File: Allow New Parent Directory

### ISSUE THREAD

**Issue by theduke** [nvim-neo-tree/neo-tree.nvim#292]
When renaming a file, check if the new path contains a parent directory that does not exist yet and create it.

Eg: `file.x` => `dir/file.x` : create `dir/` directory first.

Currently this results in an error.

**Comment by cseickel** [comment]
That is actually what the `move` command does. If you have the default mappings, just use `m`.

**Comment by theduke** [comment]
Is there any reason for splitting the functionality between move and rename?
Seems like they should just have the same behaviour.

**Comment by cseickel** [comment]
It's not really a split at all, I am just emulating what is normally found at the command line. What you requested is actually a `mv` command, not a `rename` command.

It just so happens that `mv` can also be used to `rename`. Personally, when at the command line, I always use `mv` even when I am `rename`ing because it is shorter to type and more versatile for a single file or directory.

**Comment by nyngwang** [comment]
I also had the same question before, now I only use `'move'` for renaming. While it's strange(?) that:

> It just so happens that mv can also be used to rename. [...]

I think this should imply that we actually don't need the rename functionality?

**Comment by cseickel** [comment]
> I think this should imply that we actually don't need the rename functionality?

I can certainly see why you would say that, but I disagree. To me, having different commands for different actions helps reduce accidents. I would never intentionally move a file when I meant to rename, so if it did happen it would be a typo and I would want it to fail.

Also, if I did remove the "rename" command as redundant, I would still leave "move" as "move". I would never rename "move" to "rename" because that would not be an accurate description of what the command does.

Of course, I am just talking about the default mappings, which you don't have to use at all. Feel free to map `r` to `"move"` if you want!

**Comment by nyngwang** [comment]
> I would never intentionally move a file when I meant to rename, so if it did happen it would be a typo and I would want it to fail.

This is very reasonable to me, thanks for your clarification!
