### ISSUE TITLE
Long Delay for Delete Modal

### ISSUE THREAD

**Issue by theduke** [nvim-neo-tree/neo-tree.nvim#293]
When pressing `d` there is a pretty long delay until the delete modal shows up.

Maybe related to the keybinding?

**Comment by gegoune** [comment]
https://github.com/nvim-neo-tree/neo-tree.nvim/blob/a1f5f4b15cec517d632e7335d20400cb3f410606/doc/neo-tree.txt#L319 - add `nowait` to `d` mapping (it waits for another keystroke as `dd` is a valid vim mapping).

**Comment by theduke** [comment]
The default config seems to have:

```lua
      mapping_options = {
        noawait = true,
      },
```

Doesn't that take care of setting noawait for default bindings?

**Comment by theduke** [comment]
Ah, seems like that option is set in the example setup, but not an actual default.

**Comment by cseickel** [comment]
> Would it be sensible to set this by default?

It used to be the default, but that caused problems for some people. The README should probably clarify when a suggested option is not the default. Sometimes that happens because I don't want to change defaults for existing users even though I think most people would want something other than the default setting.
