### ISSUE TITLE
Add filetype to all the buffers :NeoTreeFloat creates

### ISSUE THREAD

**Issue by s1n7ax** [nvim-neo-tree/neo-tree.nvim#313]
When I open the `:NeoTreeFloat`, plugin creates two windows, one shows the file tree and the other I believe the border. One of the buffers has the filetype `neo-tree` but not the other.

Why?
Well, use case is not related to the neo-tree at all but it would be easy for people to ignore neo-tree buffers to be excluded from other plugins. 

In my case, I have created a plugin called nvim-window-picker. I want to Ignore all the buffers that belongs to neo-tree in my plugin. I can simply add the `filetype: neo-tree` to the filter list. At the moment, neo-tree split window works as expected but not the neo-tree floating window.

https://github.com/s1n7ax/nvim-window-picker/issues/5

**Comment by MunifTanjim** [comment]
I left some comments ono https://github.com/s1n7ax/nvim-window-picker/issues/5. Let's see if that solves the issue.

Otherwise, I'll probably need to allow passing `buf_options` and `win_options` to `popup_options.border`. Although accepting all the buffer/window options for border might not be a good idea, so will need to allow only a few selected options. I'll need to think about it a little bit.

In the meantime you can use the `popup.border.bufnr` and `popup.border.winid` variables to set whatever options you need using `nvim_{buf,win}_set_option` APIs.

**Comment by cseickel** [comment]
It looks like this was handled by ignoring all floating windows, so nothing to do here.
https://github.com/s1n7ax/nvim-window-picker/issues/5#issuecomment-1107673878
