### ISSUE TITLE
How to explicitly refresh the tree manually

### ISSUE THREAD

**Issue by rockyzhang24** [nvim-neo-tree/neo-tree.nvim#352]
I know that I can use the default mapping `R` to refresh the tree if I am already in the neo-tree buffer. However, if I am not in the neo-tree buffer, how to refresh the tree? 

In other issue page, I found probably I could use `:lua require("neo-tree.sources.manager").refresh("filesystem")`, is this correct? And is there an API to refresh the tree no matter what source, i.e., not give it the source name explicitly, like `refresh("all")` so that I can bind it to a key and refresh the tree no matter source it uses by pressing this key. 

Thank you in advance for your help.

**Comment by cseickel** [comment]
`:lua require("neo-tree.sources.manager").refresh("filesystem")` is the best means to refresh.

If you want to refresh all, I'm guessing you have a specific reason that might have a more specific answer. For example, if you want to refresh all because you had a git action that the trees don't see, then you should fire a `git` event instead:
```lua
lua require("neo-tree.events").fire_event("git_event")
```

or if it is due to a file change, you could use:
```lua
lua require("neo-tree.events").fire_event("fs_event")
```

If there is some other reason that doesn't correspond to any existing events, you could easily bind your mapping to a function that calls the refresh function 3 times:

```lua
local function refresh_all()
  require("neo-tree.sources.manager").refresh("filesystem")
  require("neo-tree.sources.manager").refresh("git_status")
  require("neo-tree.sources.manager").refresh("buffers")
end

**Comment by rockyzhang24** [comment]
Okay I got. Thank you for your detailed answer.

**Comment by nyngwang** [comment]
@cseickel I really don't like the current behaviour regarding git. I have to manually refresh to clear out those false "edited marks". This happened when I just committed my changes(so no changes should be identified). Is it possible to automatically do this for us? While this thread gives a way to manually do so.

**Comment by cseickel** [comment]
I really wish there was @nyngwang , but I cannot figure out a way to do that. The only thing I can find that would actually work is to poll git every second. That seems very heavy handed to me, I'd rather improve the git status source to get people to make their git updates within neotree where I can track them.

**Comment by nyngwang** [comment]
OK, understood. Then I will use a hotfix as a workaround for now. Thanks for your explanation.
