### ISSUE TITLE
[Feature request] Show alternate sources as tabs at the top of the tree UI

### ISSUE THREAD

**Issue by akinsho** [nvim-neo-tree/neo-tree.nvim#425]
Firstly, this feature is kind of pure nice to have territory, as a user can easily do what they want without it. I do think though that it will improve discoverability. With that said, onto the actual feature.

I happened upon a screenshot of Intellij's new editor fleet and noticed that it offered separate tabs to view the git tree/source as well as history. It made me think that neo-tree offers multiple sources, but they are only accessible via the command line. You have to reopen neotree with that source specified in order to see it. Maybe there is a more ergonomic way I'm not aware of. Also, you need to remember in the moment that a source exists. I think it would be really nice if there was a visual indicator like a tab maybe using winbar or something to show multiple tabs and a mapping +/- click function to swap between them.

<img width="328" alt="image" src="https://user-images.githubusercontent.com/22454918/178691208-f7a320ec-4779-45be-a104-9f1e6c4fc67c.png">

This is sort of a "this could be cool" not sure how much work it will be on your side but essentially just floating the idea to see what you think.

**Comment by akinsho** [comment]
These things are probably old news to ex GUI editor users, but I've only ever used vim/nvim, so I'm always pretty intrigued by some of the discoverability that GUI editors tend to provide with things like this

**Comment by cseickel** [comment]
I think a Winbar would be a great way to implement this, but that is a very personal feature so maybe we could just provide a function that a user can call within their winbar if they use it.

Something like:

```lua
if vim.bo.filetype == "neo-tree" then
    vim.wo.winbar = "%!v:lua.require'neo-tree'.winbar_source_picker()"
end
```

I don't know if that is the correct syntax, but you get the idea.

**Comment by cseickel** [comment]
Also, if someone happens to use bufferline, and that bufferline provides an offset for the file tree plugin, the bufferline plugin could probably provide the feature as well.

**Comment by akinsho** [comment]
@cseickel I imagined it would be gated behind a config option, so people can enable/disable as they please. Re. providing the function, I think it will be more user-friendly to take a config option as a boolean or a list of sources. Whereas a function puts quite of the onus on a new user to do a lot of wiring up. Ultimately any mechanism that could work would be great, but I've notice a trend towards huge lumps of lua in configs (which I'm also very guilty of in my plugins) I think a function as an option should be a power tool for people looking to go wild

**Comment by akinsho** [comment]
Re. bufferline it's true that space could be used by one, but I really don't think it's the remit of a bufferline plugin to manage that sort of thing. I guess if a function was provided via the API a user could just to use it inside their config for the bufferline, but I think this falls into the remit of people going wild in their configs as opposed to the default behaviour or anything official IMO

**Comment by akinsho** [comment]
NOTE: This is all just one guy's opinion. Feel free to implement it however you wish, *if you want to at all*

**Comment by cseickel** [comment]
I agree with your points in general about a boolean config being ideal and it certainly should be the concern of this plugin and not bufferline.nvim. The problem is that nvim isn't very flexible about how these spaces can be configured. 

There is only one tabline, so if you use it and you want this picker to be in that top row, the feature has to be integrated by that buffer/tab plugin.

Likewise with winbar, it's either on for all windows or off for all windows, so you can't use the feature in Neo-tree in isolation, it has to be part of your custom config or another plugin. The good news with this one is that I suppose it can still be a boolean flag which would then override your winbar for this one window, assuming you already have a default setting for the rest of your windows which is appropriate.

The good news is that I think the syntax is the same for winbar and tabline, so I can provide a generic function that can be used in many ways.

> Feel free to implement it however you wish, if you want to at all

The funny thing is that I am not intgerested in ujsing this feature at all, but I am kind of interested in it as a technical/ui challenge. I may do it for fun, especially if more people express interest.

**Comment by cseickel** [comment]
> I might have misunderstood, but I don't think this statement is correct a winbar can definitely be applied locally to a window, so it isn't something that will interfere with other winbars 

What I meant was that you can have winbar be on just for one window (as far as I know). They can definitely have different values for different windows though. The user would need to be aware of this and configure winbar for other windows themselves. That's why I hesitate in providing it as a config, because I will inevitably get the "Neotree makes all my windows have an extra blank space at the top" issue.


> as an example I'm working a similar idea for toggleterm to show the available terminals as tabs in the winbar. 

Cool idea!

**Comment by akinsho** [comment]
@cseickel I believe you can i.e. Without the empty space if scoped locally and nil globally it won't render the space. I'm pretty sure I had such a set up in my config but didn't like the faff so just render it everywhere now

**Comment by cseickel** [comment]
> Without the empty space if scoped locally and nil globally it won't render the space.

Well that would change everything then. I know I had problems when I was setting up my own winbar, I wanted to hide it for certain windows but it didn't work for me. I found this and thought it was by design: https://github.com/neovim/neovim/issues/18660

However, I was just able to make it work as you described by setting the global option to nil and just setting a local option for one window. That means I can safely do it for Neo-tree and not worry about it turning on winbar for all windows.

**Comment by cseickel** [comment]
I'm going to call this one done for now. The feature has been released. The one item that was missing from the release was a way to navigate sources with a mapping, but that has just been added to `main` and will go out in the next release. You can change sources with the `<` / `>` keys.

Thanks @pysan3 for all your hard work on this!
