### ISSUE TITLE
position='current' file split open will change the current window buffer also

### ISSUE THREAD

**Issue by s1n7ax** [nvim-neo-tree/neo-tree.nvim#434]
https://user-images.githubusercontent.com/18459807/179344877-ffbfacf1-728b-43ba-a04b-131ed1823a0b.mp4

Steps:
* Open 'a.lua' file in neovim
* Open neo-tree in current mode
* Open 'b.lua' file in split window
* Jump back to the first window
* Run NeoTreeFocusToggle command to close the tree

Expected: 
First window should show content of 'a.lua'

Actual:
First window shows content of 'b.lua'

**Comment by cseickel** [comment]
Sorry to let this set for so long, but I am going to close it now because the scenarios you are describing are not the intended usage of the `position=current` feature, they are in fact the intended for the sidebar positions specifically. The beauty of the `current` position is that its usage is simple and obvious and does not need to be over complicated by the ability to open files in another window.

Please read this: http://vimcasts.org/blog/2013/01/oil-and-vinegar-split-windows-and-project-drawer/

Also, please do not use any of the deprecated `NeoTree*` commands, they will be removed soon. You should be using the singular `Neotree` command which takes arguments for all of it's variations.
