### ISSUE TITLE
Automatically expand path to the active file

### ISSUE THREAD

**Issue by ioreshnikov** [nvim-neo-tree/neo-tree.nvim#45]
Hey!

Is there a way to make `neo-tree` automatically expand the directory nodes to the currently edited file? For example:

1. `neo-tree` is showing `~/.config/nvim` with all directories collapsed. The currently edited file is `init.nvim`
2. I open a new file with `:e after/ftplugin/html.vim`
3. `neo-tree` automatically expands the directories `after` and `ftplugin` to show the currently edited file.

Ideally, this should also remember the manually expanded subdirectories. So if I have some other subdirectory `my/other/subdir` expanded by hand, then automatic expansion of `after/ftplugin` should not affect it; likewise, nothing opened previously by hand should not be automatically collapsed once I switch out of this subdirectory.

Best,
Ivan

**Comment by cseickel** [comment]
Not yet, but it would not be that difficult to add a "follow" option. The question is, what happens when the **follow** feature opens a folder to reveal the current file, and then you navigate to another file in a different folder? 

A. Should the prior automatically opened folder close to leave only the current file path and any manually opened folders?
B. Should it leave open any folders that were opened during your travels?

Option B is much easier, but which one is the intuitive behavior?

**Comment by cseickel** [comment]
I just realized you already thought and answered my question in your original description: option A. I am going to pin this issue to see if anyone else has a different opinion they want to add.

**Comment by ioreshnikov** [comment]
@cseickel The way I see it, if the user decided to manually expand a directory, then they did it intentionally and it would be great if any automatic behaviour respected this intent.

I didn't read the current code that you have, but I imagine that the directory nodes in the tree have an `open/closed` flag that is used  when rendering the buffer. If this guess is right, then I think it should be possible to expand this binary state to `open_manually/open_automatically/closed` and treat both `open_` states as, well, open when rendering, but treat them differently when collapsing the previously expanded directories.

However, I can also see why this is an oversimplification. For example, in this scenario we don't have a `closed_manually/closed_automatically` distinction, and I can imagine a really frustrated user who just wants `neo-tree` to keep this one directory closed when they switch to a file that is 10 levels deep.

**Comment by cseickel** [comment]
I am using NuiTree so that state is internal to the control. Of course, I can add my own property to start tracking this extra state on my own. I do already collect open folders and re-open them on every refresh or navigation to a new root.

In theory this does not sound to difficult, but my spidey sense is tingling on this one. There's a lot of potential for bugs in this type of feature.

I would personally use the feature if we had it. I think it should be added, but not sure if I am ready to start work on it yet.

**Comment by cseickel** [comment]
This just landed in **main** and it works exactly as you originally requested. To turn it on, add this option to your config:

```lua
      require("neo-tree").setup({
        filesystem = {
          follow_current_file = true
        }
      })
```

If you get a chance to try it out before it is released to 1.x, let me know if it is working as expected.

**Comment by ioreshnikov** [comment]
@cseickel Holy cow it's cool! It works exactly as I saw it! Many thanks, great!

**Comment by EpsilonKu** [comment]
@cseickel I enabled `follow_current_file`, but seems it doesn't work.

**Comment by cseickel** [comment]
It's probably a typo or you forgot to source/restart and then `:PackerCompile` (if using packer).

Can you restart nvim, run `:PackerCompile`, then post your config if it's still not working?
