### ISSUE TITLE
Deleting a terminal buffer deletes project root

### ISSUE THREAD

**Issue by Taaqif** [nvim-neo-tree/neo-tree.nvim#478]
Something extremely frustrating happened this morning, my entire project director was deleted after attempting to delete a terminal buffer.

I use LazyGit to manage my git repo's and use the lazygit plugin https://github.com/kdheepak/lazygit.nvim.
When opening the buffer preview list, I saw several instances of the terminal show up, I attempted to delete these terminal buffers using the `d` command and after confirming, my entire project directory was deleted 
![image](https://user-images.githubusercontent.com/1954204/184053352-1aa9f830-6818-4e2d-9b81-9fa7d2d9c9cf.png)

I can replicate this by creating a new directory, creating a few files, opening lazy git plugin (as above), closing that window using `q` and showing the buffer list from neo-tree then attempting to delete the terminal buffer.

As you can imagine, I had lost a significant chunk of work and it would be good to either prevent this from deleting the entire directory or not allowing the ability to delete terminal buffers

**Comment by cseickel** [comment]
The problem here is that `d` is mapped to `delete`, which  deletes files and directories. A terminal has a path, which is its current working directory, so issuing a `delete` command on it will delete that directory.

What you were trying to do is to delete the **buffer**, which is a different command called `delete_buffer` that is mapped to `bd`.

In all fairness, the confirmation is very clear that you are about to delete the directory and that the directory is not empty.

I can't imagine there ever being a time where someone would intentionally issue a `delete` command on a terminal, so I think the correct thing to do here is to only allow that command to run on nodes of type `file` or `directory`. I'll do this now and the change will go out in the next release.

**Comment by Taaqif** [comment]
Thanks for this, I see my color scheme actually has white text on the white header which is likely why I missed the confirmation message and hit `y` not knowing the consequences.

Definitely error on my part as I should have realised, it would still be great to safeguard any future instances of this through your suggestion of only executing this on `file` or `directory` nodes!
