### ISSUE TITLE
[Bug] Inapplicable mappings cause errors with source selector enabled.

### ISSUE THREAD

**Issue by akinsho** [nvim-neo-tree/neo-tree.nvim#513]
When using the source selector having added mappings to replace the native filter mapping
```lua
window = {
  mappings = {
    ['/'] = 'noop',
    ['g/'] = 'fuzzy_finder',
 }
}
```
When switching to other source using `>` an error is shown that the mapping is not found
<img width="537" alt="image" src="https://user-images.githubusercontent.com/22454918/189841733-454d5713-f655-400c-a5a3-39a839880670.png">

**Comment by cseickel** [comment]
The problem here is that the `'fuzzy_finder'` command is specific to the `filesystem` source and not available to the others. This means that it cannot be specified in the global mappings section since it will produce that error for the other sources.

The fix is to just move it to the `filesystem` section of your config:

```lua
filesystem = {
  window = {
    mappings = {
      ['/'] = 'noop',
      ['g/'] = 'fuzzy_finder',
   }
  }
}
```

**Comment by akinsho** [comment]
Thanks @cseickel, I didn't realize that was possible 👍🏿
