### ISSUE TITLE
Add symbolic link targets

### ISSUE THREAD

**Issue by jgottzen** [nvim-neo-tree/neo-tree.nvim#53]
Would you be interested in a pull request adding a component for showing the target of symbolic links?

This is one feature I miss from nvim-tree.

This is how it would currently look:
![screenshot_2022-01-14-18:01:06](https://user-images.githubusercontent.com/905941/149558550-48e2d8fa-fa31-4892-a0c7-256cefc43ef9.png)

**Comment by cseickel** [comment]
Absolutely! In this case, I would say that it would be good to put the component in the examples as a commented out component rather than enabled by default. As we gather more components that are not in the default config, we'll probably add a wiki page to list them all with screenshot examples.

Also, please make sure your PR is targeting main, which is ahead of the the default branch (1.x).
