### ISSUE TITLE
`git_status` Invalid mapping for <cr>: nil, etc.

### ISSUE THREAD

**Issue by nyngwang** [nvim-neo-tree/neo-tree.nvim#530]
I'm reviewing notifications on old issues, so I'm not sure whether this would have been resolved or not, but here it is:

I put my configuration in `setup.window.mappings`:

```lua
mappings = {
  -- root behaviour.
  ['-'] = 'navigate_up',
  ['<C-]>'] = 'set_root',

  -- open files.
  ['<2-LeftMouse>'] = 'shift_M_open',
  ['<cr>'] = 'shift_M_open',
  ['w'] = 'picker_open',
  ['o'] = 'macOS_open',
  ['%'] = 'open_vsplit',
  ['"'] = 'open_split',
```

but according to the warning some of these mappings are not received/detected.

<img src="https://user-images.githubusercontent.com/24765272/191168884-c5223473-5f60-4bf7-b0cf-9632a22b2936.png" width="400">

**Comment by cseickel** [comment]
All of the errors are from commands that do not exist. I'm guessing they might be custom commands that you have defined elsewhere in your config. If so, please be aware that you cannot define a command globally, they must be defined for each source that will use them. This is because most commands have to be adjusted to work correctly for the source they are operating on. I cases where the command is generic enough that it will work across sources without modification, you can just declare a reference to it outside of your setup call and repeat the assignment in the `commands` section of every source.

**Comment by nyngwang** [comment]
I moved `setup.window.mappings` back to `setup.filesystem.window.mappings` and got rid of these warnings. But this might not be the correct way according to your words. Can close this for now since if I encounter warnings/errors related to this change I will reopen it.

**Comment by cseickel** [comment]
> I moved `setup.window.mappings` back to `setup.filesystem.window.mappings` and got rid of these warnings. But this might not be the correct way according to your words.

This is the ideal solution if you only use these mappings in the filesystem source.

**Comment by nyngwang** [comment]
> This is the ideal solution if you only use these mappings in the filesystem source.

Actually, I only have `setup.filesystem` and `setup.window` on my config for neo-tree.nvim, so I think this is my case and I haven't made use of other sources? (What are the other sources, btw?)

**Comment by cseickel** [comment]
> (What are the other sources, btw?)

The other built-in sources are `git_status` and `buffers`: https://github.com/nvim-neo-tree/neo-tree.nvim#sources

There are also a few external sources:https://github.com/nvim-neo-tree/neo-tree.nvim/wiki/External-Sources

**Comment by nyngwang** [comment]
With the references you provided and some lookups at the default.lua, It's very clear now! Thank you! (It turns out that my idea of "moving settings to top-level to avoid redundancy" has leaded to some pitfalls.)
