### ISSUE TITLE
event = 'file_opened' not work with fuzzy finder

### ISSUE THREAD

**Issue by LoneExile** [nvim-neo-tree/neo-tree.nvim#543]
event = 'file_opened' does not work with fuzzy finder.
expect to close Neotree when opening the file. did I do something wrong?

```lua
  event_handlers = {
    {
      event = 'file_opened',
      handler = function(file_path)
        require('neo-tree').close_all()
      end,
    },
  },
```

**Comment by cseickel** [comment]
You're not doing anything wrong. The event actually fires and neo-tree closes, but then it is quickly re-opened as the final step of the search reset routine. It happens so fast you can't see it.

While this is technically a bug, it's not a high priority because I feel that it is much more logical to use the `float` or `current` position if your intention is to open Neo-tree just long enough to fuzzy find and open a file. Both of those choices work naturally with this workflow without any extra configuration.

If you are interested, I actually have these special functions in my config that opens neo-tree and jumps me straight into fuzzy finder for a quick file open:

```lua
local openNeotree = function ()
  local cmd = require("neo-tree.command")
  local manager = require("neo-tree.sources.manager")
  cmd.execute({
    action = "focus",
    source = "filesystem",
    position = "current"
  })
  local tabnr = vim.api.nvim_get_current_tabpage()
  local winid = vim.api.nvim_get_current_win()
  local state = manager.get_state("filesystem", tabnr, winid)
  return state
end

local findDirectory = function ()
  local filter = require("neo-tree.sources.filesystem.lib.filter")
  local state = openNeotree()
  filter.show_filter(state, true, "directory")
end

local findFile = function ()
  local filter = require("neo-tree.sources.filesystem.lib.filter")
  local state = openNeotree()
  filter.show_filter(state, true, true)
end
```

I then have `findFile()` mapped to `<leader>ff` and `findDirectory()` mapped to `<leader>fd`.

**Comment by LoneExile** [comment]
> it is quickly re-opened as the final step of the search reset routine. It happens so fast you can't see it.

yeah so quickly
I tried to close it with this, but it still reopened after a fuzzy search.
Thank you for the snippet, BTW.

```lua
local group = vim.api.nvim_create_augroup('neotreeEnter', { clear = true })
local events = { 'BufEnter', 'BufWinEnter', 'CursorMoved' }
vim.api.nvim_create_autocmd(events, {
  pattern = { '*' },
  callback = function()
    local fileType = vim.api.nvim_buf_get_option(0, 'filetype')
    local buftype = vim.api.nvim_buf_get_option(0, 'buftype')
    if (fileType ~= 'neo-tree' and buftype ~= 'nofile') or (buftype ~= 'nofile' and fileType ~= '') then
      require('neo-tree').close_all()
      vim.cmd('Neotree close')
      vim.notify('fileType: ' .. fileType .. ' buftype: ' .. buftype)
    end
  end,
  group = group,
})
```

**Comment by devenv** [comment]
Also interested if there is a way to close neotree after choosing a file.

**Comment by cseickel** [comment]
> Also interested if there is a way to close neotree after choosing a file.

If that's what you want then using the "current" or "float" positions would be more appropriate.

**Comment by pysan3** [comment]
This should eliminate all the hassles. https://github.com/nvim-neo-tree/neo-tree.nvim/pull/979. 

If it does solve your issue, please close this.
