### ISSUE TITLE
Issues with other buffers that aren't files

### ISSUE THREAD

**Issue by lopi-py** [nvim-neo-tree/neo-tree.nvim#564]
When theres not a window with a file and theres one which is not, neo-tree will open the fille in that window
https://gyazo.com/552f09d7df2b25daafac664974eed572

**Comment by cseickel** [comment]
Would it be accurate to rename this as "Neo-tree should not open files in floating windows"?

**Comment by lopi-py** [comment]
It also happens on a terminal buffer which is a horizontal split

**Comment by cseickel** [comment]
> It also happens on a terminal buffer which is a horizontal split

For me, that is expected behavior. Not all of my terminals are ever present at a particular place. I often just toggle to a terminal in whatever window I am in at the moment then toggle back to the file when I am done.

Perhaps, in addition to never opening a file in a float, we should add a way to exclude specific windows from being chosen. Filetype is commonly used for this sort of thing but it's not the only way. The most flexible would be to provide a callback function where the user is provided a window handle and is expected to return a boolean indicating whether it can be used.

**Comment by lopi-py** [comment]
> For me, that is expected behavior.

It's annoying for me because I use toggleterm and it sets the buffer background a little darker also it doesn't show numbers and thats annoying(for file buffers), I think that a function would be nice

**Comment by trevarj** [comment]
This is affecting my workflow with toggleterm/term buffer too.

1. Doing work inside a term
2. Focus neotree
3. Open a file
4. File is opened in the term buffer (small horizontally split) since it was the last focused 😞

**Comment by mokafolio** [comment]
I am having the same problem and would really appreciate a solution :)

**Comment by airtonix** [comment]
#802

**Comment by cseickel** [comment]
https://github.com/nvim-neo-tree/neo-tree.nvim/issues/802#issuecomment-1465088198
