### ISSUE TITLE
Plugin Integration Questions

### ISSUE THREAD

**Issue by miversen33** [nvim-neo-tree/neo-tree.nvim#574]
Heyo! Its been a bit since we have chatted, I am beginning work on getting Netman integrated into Neo-tree but to be honest, I dont really know where to begin. I started looking at the diagnostics plugin but I can't quite make out how to get started with it (I am just kinda reverse engineering how that plugin works). [The wiki has a very brief section on External Sources](https://github.com/nvim-neo-tree/neo-tree.nvim/wiki/External-Sources) but I'm not really figuring out how to get started.

I assume I am missing something in the docs, kinda hoping you could help point me in the right direction.

I appreciate you :)

**Comment by cseickel** [comment]
Hey @miversen33 , sorry I haven't responded sooner. I have been crazy busy this last week. I'm afraid I removed the example source from this repo that served as documentation when we switched over to external sources and I didn't replace that with documentation...

I did move it to here and forgot about it: https://github.com/nvim-neo-tree/example-source

It may not be complete but it's enough to get you started if you clone it as your starting point. I always say the internal `buffers` source is a good example because it has all the functionality but is ultimately as simple as a source can get.

**Comment by miversen33** [comment]
No worries! I will pick through that and get started! After having a peek at how [zk](https://github.com/prncss-xyz/neo-tree-zk.nvim) is integrated, I think I have a general idea of how to get started. It looks like I can get away with having netman be an external source which is nice (for now).

As Netman will _eventually_ be showing files within Neo-tree, I would like the source to match whatever style is being used by the files source (consistency is good). If I need help, am I free to ping you with future questions?
