### ISSUE TITLE
[Question] Respecting .ignore file

### ISSUE THREAD

**Issue by YasserKa** [nvim-neo-tree/neo-tree.nvim#586]
Some tools like `rg` and `fd` respect `.ignore` files when hiding files.

I sometimes include files to `.gitignore` that I always want to include in `rg` and `fd` output.

so I add something like this in `.ignore`
```
!dont_ignore_file
```
Is it possible for neo-tree to respect these files as well?

**Comment by cseickel** [comment]
Yes, you'll want to use the `filesystem.filtered_items.always_show` or `always_show_by_pattern` options. See
```
:h neo-tree-filtered-items
```
for more information.

**Comment by YasserKa** [comment]
From my understanding, these options work globally (in every project in the system). Is it possible to override it on a project level?

**Comment by cseickel** [comment]
You could use the `always_show_by_pattern` list and include project paths in the patterns, like:

```lua
filesystem = {
  filtered_items = {
    always_show_by_pattern = {
      "*/project_a/file_to_show.json",
      "*/project_b/*/specific_file_in_any_subfolder.lock",
      "*/project_c/*.ext",
    }
  }
}
```

If you are looking for the ability to add a special `.do_not_ignore.neo-tree` file to each project root, it does not do that.

**Comment by Olical** [comment]
I was going to open a duplicate issue, so instead I'll just try to leave a polite nod here: I'd love it to respect `.ignore` files too so I can exclude files from all of my tooling while keeping them in git 😄 

My use case is compiling Fennel Neovim config and plugins to Lua and committing that Lua code into the repo since it's AOT compiled and I don't want my users to have to go through a compile step to use my stuff. Buuut I also don't really need to see the `.lua` file next to my `.fnl` file when browsing my source. Telescope respects `.ignore` because `rg` does, it'd be lovely if Neotree did too.

Feel free to ignore this! Just leaving my thoughts here, maybe more people will find it on Google, realise the same and not open any more issues on the topic.

**Comment by medv** [comment]
> Yes, you'll want to use the `filesystem.filtered_items.always_show` or `always_show_by_pattern` options. See
> 
> ```
> :h neo-tree-filtered-items
> ```
> 
> for more information.

Was the `always_show_by_pattern` option removed?
It would be really nice to have so that `.env*` could be added to support `.env.development`, `.env.test` and so forth. The exact names are not always known ahead of time, but are respected as a convention in many (at least) node projects.

**Comment by cseickel** [comment]
> Was the `always_show_by_pattern` option removed?

Honestly, I don't think it ever existed, I can't find any evidence of it. I'm not sure what I was thinking when I posted that comment.

**Comment by medv** [comment]
Are there any plans for it at all, or should I hard code whatever I need to ensure is visible? Either is fine at the end of the day, was just confused with that option turning up in this issue but nowhere else heh

**Comment by cseickel** [comment]
No plans right now, but I would definitely merge it if someone put up a PR for this.
