### ISSUE TITLE
Too slow on a big monorepo

### ISSUE THREAD

**Issue by mmrath** [nvim-neo-tree/neo-tree.nvim#589]
Not sure if this is a know issue or already reported. I have just setup neo tree and tried opening a big mono repo. It is noticeably slower. I have replaced it with nvim-tree and it opens quite smooth so likely it is not because of other plugins. Wondering what I details I can provide to get some help investigate this.

Here is my complete init file: https://gist.github.com/mmrath/5f0c24d0d95eb7f5b81d3fa1ed49d62e

**Comment by cseickel** [comment]
Here are some relevant options you can experiment with in your setup:
https://github.com/nvim-neo-tree/neo-tree.nvim/blob/ab8ca9fac52949d7a741b538c5d9c3898cd0f45a/lua/neo-tree/defaults.lua#L18-L29

https://github.com/nvim-neo-tree/neo-tree.nvim/blob/ab8ca9fac52949d7a741b538c5d9c3898cd0f45a/lua/neo-tree/defaults.lua#L362-L364

All of the git_status stuff is async by default, so I would start by setting this to false and see if that helps:
https://github.com/nvim-neo-tree/neo-tree.nvim/blob/ab8ca9fac52949d7a741b538c5d9c3898cd0f45a/lua/neo-tree/defaults.lua#L381

**Comment by musjj** [comment]
This is most likely because `git.ignored.mark_ignored` is synchronous. This is especially bad on Windows, because of how slow the Windows port of git is.
There's also a few other blocking git operations involving getting the root directory that also causes a few hiccups when refreshing.
I have a hacked up local repository that asyncifies these operations, if no one else is interested on working on it, I'll try to clean them up into a few PRs in the next few days.
