### ISSUE TITLE
Modal editing in rename and copy to popups

### ISSUE THREAD

**Issue by gerazov** [nvim-neo-tree/neo-tree.nvim#602]
Great plugin :sunglasses: 

It might be there, but couldn't find it - it would be nice to have normal mode available when renaming `r` or copying`c`  files in `neo-tree`. It's really well done in [lspsaga](https://github.com/glepnir/lspsaga.nvim) where the user can config if they prefer to enter the rename popup in insert or normal mode:

```vim
rename_action_quit = '<C-c>',
rename_in_select = true,
```

The downside would be that `<esc>` would now change to Normal mode instead of exiting, but maybe `<esc>` in Normal mode can exit ...

**Comment by nagy135** [comment]
Was just about to create the same issue. I think getting into normal mode by default can be confusing for new users so it should be "opt in" feature. But as I see it, if your input is already populated with text, you should be in normal mode. Currently 99% of times I have to "backpedal" to the start since changing extension is pretty rare (at least for me)

**Comment by cseickel** [comment]
I agree that sometimes I wish I could edit these popups in normal mode, but it doesn't quite cross the threshold where I would personally do the work to make it happen. I would gladly accept a PR that adds this as an option.

If it helps, you can use vim's built in input functionality instead of Neo-tree's custom popups by changing the config option:

https://github.com/nvim-neo-tree/neo-tree.nvim/blob/73a90f6a736b51168ed05d89ed8872f75b98471c/lua/neo-tree/defaults.lua#L42

**Comment by DasOhmoff** [comment]
I would also love to have this. Renaming files is a real pain right now

**Comment by alanoliveira** [comment]
I also would like this feature.

For now I'm using this workaround
```lua
-- ftplugin/neo-tree-popup.lua

local timer = vim.loop.new_timer()
-- Timer is necessary because the maps are added after the popup is created
timer:start(100, 0, vim.schedule_wrap(function()
  local esc_maps = vim.tbl_filter(function(m)
    return m.lhs == "<Esc>"
  end, vim.api.nvim_buf_get_keymap(0, "i"))

  if #esc_maps > 1 then
    vim.notify("More than 1 '<Esc>' maps were found. Aborting.", "Error")
    return
  end

  local close_map = esc_maps[1]
  vim.keymap.del(close_map.mode, close_map.lhs, { buffer = close_map.buffer })
  vim.keymap.set("n", close_map.lhs, close_map.callback, { buffer = close_map.buffer })
end))
```

**Comment by am1fat32** [comment]
It would be so nice to have this option!

**Comment by pysan3** [comment]
@am1fat32 did you see this? https://github.com/nvim-neo-tree/neo-tree.nvim/pull/1043

If I'm not mistaken, there should be a way to access normal mode now. I just can't tell cuz I don't use it myself...

**Comment by swaroopsm** [comment]
@am1fat32 

FWIW:
There is a setting called: `enable_normal_mode_for_inputs` that needs to be set to `true`. I got it working by adding the following in my `.lua` config file (FYI: I am using https://github.com/folke/lazy.nvim as my plugin manager):

```lua
  {
    'nvim-neo-tree/neo-tree.nvim',
    opts = {
      enable_normal_mode_for_inputs = true
    }
  }

```


Thanks @pysan3 for linking the PR, that helped! :)

**Comment by am1fat32** [comment]
@pysan3 , @swaroopsm 
Finally, I fill that my config is consistent.
Thank you so much, guys!

**Comment by gerazov** [comment]
Awesome :love_you_gesture: 

Closing this :pray:
