### ISSUE TITLE
[Feature request] nvim-tree `hijack_cursor` functionality

### ISSUE THREAD

**Issue by Racle** [nvim-neo-tree/neo-tree.nvim#604]
"Keeps the cursor on the first letter of the filename when moving in the tree."

In my opinion it's little easier (or more "pleasant" to eye) to follow where cursor is when it's always on first letter of dir/file.

When moving cursor with `jk` and open/close nodes with `hl`, with this feature in nvim-tree that feels much better.

https://github.com/nvim-tree/nvim-tree.lua/blob/9e87ee2d6e86f37ff09cb74ec7dcf2ac984a01e9/doc/nvim-tree-lua.txt#L478

**Comment by miversen33** [comment]
This _should_ be relatively trivial to do.
In **theory** all that is needed is some simple string logic to find the first location in the line of the "name" of the node, and set the `col` value to that instead of 0.

[Source code link](https://github.com/nvim-neo-tree/neo-tree.nvim/blob/8ac4240afc7dc8ef1dbf3f816642bc3e1a4192cb/lua/neo-tree/ui/renderer.lua#L434-L439)

This is a very small area for touching, basically add a bit of logic after 439 (the space indent) to determine the correct column for the cursor.

**Comment by ashkan117** [comment]
Attempting to tackle this one as an fyi

**Comment by miversen33** [comment]
@ashkan117 When you have some code that you would like to have reviewed, feel free to submit a PR against [the main branch](https://github.com/nvim-neo-tree/neo-tree.nvim/tree/main)

I will see the PR but also I am _really_ bad at replying to notifications so feel free to tag me on it so I can review it :)

**Comment by ashkan117** [comment]
Am I right in guessing that the focus node is not triggered with hjkl movements? I can see that eventually something triggers the method then the col gets updated to the correct thing.

**Comment by miversen33** [comment]
I would not think that `hjkl` would trigger the `focus_node` function. 

> I can see that eventually something triggers the method then the col gets updated to the correct thing.

I don't know what you mean here. Is this an issue? If so, could you elaborate? I'm glad you're getting progress either way :)

**Comment by cseickel** [comment]
> Am I right in guessing that the focus node is not triggered with hjkl movements?

That's correct. It is used to restore the focused node after a refresh, for the "reveal" commands, and for the `follow_current_file` option.

**Comment by ashkan117** [comment]
Ok that makes sense. I think in  my case the reveal command was triggering the change I saw. Is there a place I should move my logic then? Since in my head the col should be reevaluated on moves and focus_node?

Basically my issue is that I am not sure where to put the logic that determines the col of the node
