### ISSUE TITLE
filesystem.follow_current_file = true only works for float if tree is opened first

### ISSUE THREAD

**Issue by catgoose** [nvim-neo-tree/neo-tree.nvim#610]
I primarily use neotree as the float tree.  If I pick a file using telescope, the float does not follow the file unless I open tree first.

![image](https://user-images.githubusercontent.com/21010072/202223604-75b14299-cfed-41d1-bd18-4fb656d79aab.png)

Opening tree:

![image](https://user-images.githubusercontent.com/21010072/202223692-64f9fcc8-b2fb-40dc-8c35-14c0853bb6c2.png)

Then opening float:

![image](https://user-images.githubusercontent.com/21010072/202223761-10c8d354-84f8-4f72-aace-1c7a4a0c62d5.png)

**Comment by lucasrabiec** [comment]
I have the same issue with the floating tree, any ideas?

**Comment by cseickel** [comment]
follow_current_file does not amke sense for a floating tree because the tree should not be open when you are switching files from somewhere else. I think what you are looking for is the `reveal` argument.

```
: Neotree float reveal
```

**Comment by lucasrabiec** [comment]
> follow_current_file does not make sense for a floating tree because the tree should not be open when you are switching files from somewhere else. I think what you are looking for is the `reveal` argument.
> 
> ```
> : Neotree float reveal
> ```

Good point, TY, this is what I need

**Comment by lucasrabiec** [comment]
@catgoose do you facing the issue that I described above?

**Comment by catgoose** [comment]
> @catgoose do you facing the issue that I described above?

No it works as I expect.  Here is my lazy.nvim config for neotree:

```lua
return {
	"nvim-neo-tree/neo-tree.nvim",
	init = function()
		vim.g.neo_tree_remove_legacy_commands = 1
	end,
	opts = opts,
	branch = "v2.x",
	dependencies = {
		"nvim-lua/plenary.nvim",
		"kyazdani42/nvim-web-devicons",
		"MunifTanjim/nui.nvim",
		"s1n7ax/nvim-window-picker",
	},
	cmd = "Neotree",
	keys = {
		m("<leader>m", [[Neotree float reveal]]),
	},
}
```

`m` is a wrapper function for creating keybindings in lazy.

**Comment by lucasrabiec** [comment]
Ok, but what happens when you open the file through a telescope that is outside the cwd, and then hit <leader>m? For me (after changing cwd) it reveals the file only within this file's directory, not with the whole scope of the project's root.

**Comment by cseickel** [comment]
> When I open `<leader>e` for the first time it shows only the opened file's current directory (e.g. component directory). When I close it and open it again (with the same shortcut) then it shows the project's root directory with the revealed file. Do you have any idea why?

My first guess would be that the function is just returning the wrong directory. I would start by adding a print statement to see what value it is actually giving you. You can also try running that command manually to see if it does the same thing or not:

```
:Neotree reveal dir=../../enter/your/path/to/project/root
```

You don;t need the `eeveal_force_cwd` in this case, it won't do anything if you are passing teh correct project root.

**Comment by lucasrabiec** [comment]
I checked it and the function returns the correct project's root (popup). When I switch files inside cwd, the reveal works properly, but when I open a file outside the cwd (through telescope old files) it asks me for changing cwd to this file directory instead of keeping its root.
![CleanShot 2023-03-29 at 09 30 56@2x](https://user-images.githubusercontent.com/9741188/228459593-44d34323-8186-4f10-84db-80670dcb4d15.png)
Then if I type `y` it reveals a file only in that file's directory scope.
If I type `n` it doesn't reveal the file, only shows the project's root with all folders collapsed.
Then if I close Neotree and open it again it works as expected in both cases.

**Comment by cseickel** [comment]
I see what's wrong, you found a bug. If you answer `n` to that prompt it would work correctly. The problem here is that the check for whether a reveled file is in the current working directory does not check the directory you requested as the root, it only checks what is your current working directory. I'll open a new issue for this.
