### ISSUE TITLE
`auto_expand_width` gets caught in infinite loop and hangs neovim

### ISSUE THREAD

**Issue by cseickel** [nvim-neo-tree/neo-tree.nvim#624]
I've noticed that with `window.auto_expand_width` enabled, sometimes neovim will freeze when I open neo-tree as a sidebar. I njust tailed the logs when this happened and saw this scrolling by:
![image](https://user-images.githubusercontent.com/5160605/204097694-8ecd44bd-7796-431d-8645-5c720bb8d7b8.png)

Related to #580 
@pysan3 Can you take a look at this?

**Comment by pysan3** [comment]
Hi, I don't have a pc with me right now so I can't test it right now but it seems that the estimated length of the expanded width is too big that it cannot fit the nvim window. 

When there is not enough width for the expanded width, it tries to expand more indefinitely falling into an infinite loop which is causing the nvim to freeze. 

I see that the estimated width is over 10,000 but did you purposely put a very very long file name?
Or maybe expanding a recursive directory symlink might explain this problem?

Could you give me a screenshot shot of the sidepanel when setting it off but with a quite big window.width in the first place?

**Comment by pysan3** [comment]
Oh, the estimated width increments one by one. 

This might be a bug in estimating the required width of the resulting panel. 

Could you send me your whole neo-tree configuration because I didn't face this issue with my setup?

**Comment by cseickel** [comment]
> I see that the estimated width is over 10,000 but did you purposely put a very very long file name?
> Or maybe expanding a recursive directory symlink might explain this problem?

This is just a standard set of files, nothing particularly long and it shouldn't be opening folders recursively.  Here is my current config: https://github.com/cseickel/dotfiles/blob/e4189bff222470ad07eeb9c947b4cbc4848b6a86/config/nvim/lua/plugins/config/neo-tree.lua#L2-L294

**Comment by pysan3** [comment]
Thanks.

One thing I'm concerned is that the width required is not aligned with the strwidth of the content, and I had to add `1` in order to align with what is shown in the window.
[Here](https://github.com/nvim-neo-tree/neo-tree.nvim/blob/e00391097df82d246c75117cef4d7add864d4eaf/lua/neo-tree/ui/renderer.lua#L346)

Can you guess where this `1` is coming from, and is this actually calculating the width of the window accurately?

**Comment by pysan3** [comment]
> When there is not enough width for the expanded width, it tries to expand more indefinitely falling into an infinite loop which is causing the nvim to freeze.

Do you know any `vim.api.xxx` or something that tells the maximum window width available in current terminal?
If there's any, changing this line could solve the problem.
[`huge_number`](https://github.com/nvim-neo-tree/neo-tree.nvim/blob/e00391097df82d246c75117cef4d7add864d4eaf/lua/neo-tree/sources/common/container.lua#L190)

```diff
- local huge_number = 2000
+ local huge_number = vim.api.nvim_give_me_the_maximum_possible_window_width(0)
```

**Comment by cseickel** [comment]
I think that would be `vim.o.columns`

**Comment by pysan3** [comment]
I am very sorry to bother you but could you do these tests with the changes?

1. Change `local huge_number = 2000` -> `local huge_number = vim.o.columns`
2. Use [this config](https://git.esslab.jp/takuto/dotfiles/-/blob/master/nlua/11-uiline-config/neo-tree.lua) instead of yours

I was able to replicate this issue with your configuration but it simply never occurs with my settings, and I don't find any option that is suspicious.
It might be caused by some combinations of plugins such as that scrolling bar on the right side? in your config which I don't know which plugin is doing that.

**Comment by pysan3** [comment]
> One thing I'm concerned is that the width required is not aligned with the strwidth of the content, and I had to add 1 in order to align with what is shown in the window.
[Here](https://github.com/nvim-neo-tree/neo-tree.nvim/blob/e00391097df82d246c75117cef4d7add864d4eaf/lua/neo-tree/ui/renderer.lua#L346)

> Can you guess where this 1 is coming from, and is this actually calculating the width of the window accurately?

Ok, so it seems that this `+ 1` is what is causing problem on your case.
I think I got something wrong somewhere not related to this plugin so let's remove this `+ 1` for now.
