### ISSUE TITLE
the dir argument doest not work as expected

### ISSUE THREAD

**Issue by changyiyao** [nvim-neo-tree/neo-tree.nvim#678]
Neotree dir=path_var does not show filesystem tree with setting root to path_var, but always setting pwd(current working directory) instead.

I wonder whether I misuse the dir argument

**Comment by nyngwang** [comment]
You might have this option set to `true`:

```lua
filesystem = {
  bind_to_cwd = true, -- sync neo-tree and vim's cwd.
```

and I just tested a hardcoded one like `Neotree dir=~/.config` and it works. So it might be that you somehow always set that variable to a fixed value.

**Comment by cseickel** [comment]
I tested it out and it works fine for me.

I would say you have some kind of autocmd or other plugin that is changing the cwd on you. I'm going to close this for now because I am certain that this is the case. If you can come up with a minimal config to recreate the problem with only neo-tree installed, go ahead and re-open the issue with that information.
