### ISSUE TITLE
netrw hijack current doesn't reset options after opening a file

### ISSUE THREAD

**Issue by mehalter** [nvim-neo-tree/neo-tree.nvim#684]
I am using neo-tree with the `hijack_netrw_behavior = "open_current"` and when I run `nvim .` and select a file `neo-tree` is not appropriately setting the options back to what they should be before it was opened. I would expect it to save the values of the options before the window is opened in the buffer, then set them back appropriately when neo-tree is closed.

**Comment by cseickel** [comment]
I don't do anything to explicitly save options and restore them. It's actually not necessary because all options that neo-tree applies are set with `setlocal`.

The problem in the linked issue is tied specifically to opening new buffers from a neo-tree window, which seem to take on whatever settings were applied in the prior buffer. So it's not a matter of restoring previous settings so much as it's a matter of applying the default settings for the first time instead of taking the local settings from the prior buffer.

I've never noticed this before because I tend to explicitly set the things I care about in filetype autocamds.

There's probably an option that controls this behavior, I'll look around.

**Comment by mehalter** [comment]
@cseickel this is because of the `setlocal` options. When netrw hijack uses the `current` it is using the same window that the buffer will be in if I open a file or simply close neo-tree. `setlocal` here is controlling buffer and window level options. `wrap` here being a window level option. So it is changing it for the window which is still there for the file when `neo-tree` is closed. `wrap` is specifically not a buffer level options (check with `:h wrap`)

**Comment by mehalter** [comment]
Also in the linked issue we are setting up the options prior to `neo-tree` being run. When I go in and manually remove the `setlocal` options from the source code this works as intended because the options are not being overwritten by `neo-tree` and then not being set back.

**Comment by cseickel** [comment]
> `wrap` is specifically not a buffer level options (check with `:h wrap`)

I guess I will need to add a save / restore step then. I'm surprised this hasn't come up before.

**Comment by cseickel** [comment]
A fix has been merged to `main`. I'm going to use it for a day and make sure it's solid before releasing. If you are able to test it out as well, please do and let me know if you have any issues.

**Comment by mehalter** [comment]
I'll give it a test as well for the next day or so. Thanks for looking into it!

**Comment by cseickel** [comment]
I did find some glitchy behavior today where it restored the wrong settings to certain buffers, namely terminals that got line numbers. I think I fixed that with the latest which was just merged from #693.

**Comment by ZhaoZuohong** [comment]
I've been testing the master branch of neo-tree today, and it looks like there is no problem until now.

**Comment by mehalter** [comment]
What problem have you found @ZhaoZuohong ? Also what do you mean that there was no problem before?

**Comment by ZhaoZuohong** [comment]
@mehalter I mean I was testing latest commit of neo-tree with AstroNvim. When I open file from netrw mode of neo-tree, there is a message says: `[Neo-tree INFO] Window settings restored` and when I check the status of buffer with `:set wrap?`, it says `wrap` which is the correct.
