### ISSUE TITLE
Use Everything for file search

### ISSUE THREAD

**Issue by DasGandlaf** [nvim-neo-tree/neo-tree.nvim#691]
Hi!
I love this plugin, great work 👍 
One thing I wish was improved, is the finder. Currently, if you have a lot of files, or you are searching outside of your project, the finding is extremely slow.
There is this software: https://www.voidtools.com/support/everything/command_line_interface/
With it, you can search for files on your OS extremely fast. It is virtually instant. If there maybe was an option to use that software, this finding feature would be improved a ton, and a lot more useful, as you could literally search through an entire disc for the needed file, in a matter of milliseconds.

**Comment by cseickel** [comment]
> I love this plugin, great work

Thanks!

> Currently, if you have a lot of files, or you are searching outside of your project, the finding is extremely slow.

Honestly, I don't think it is the underlying search tool that is slow at all. I use `fd` if installed which is extremely fast as it is. Even the fallback `find` is still very fast. The delay comes from all of the decorations (git, lsp, modified flag, etc) and rendering work that neo-tree does. I would love to make it faster, but I don't think using a new find program will really do it.

**Comment by DasGandlaf** [comment]
Maybe this is a problem on my part? Because when I am searching for a bigger directory, outside of a project, it more than 30 seconds. I thought this was just so long, because it was not meant to search for so many files?
How long does a search of a larger scope take for you, generally?

**Comment by cseickel** [comment]
For me, slow in a big directory is a lag of 1 second from my last keystroke. Worst case is 5 seconds. 

Are you on Windows? If not, can you tell me what version of `fd` or `find` you have installed?

**Comment by x3rAx** [comment]
"Everything" is a Windows only directory indexer. It runs in the background and monitors the indexed locations for changes, that's why it is so fast. `fd` and `find` on the other hand do a search *every time* they are queried, so they are naturally slower than "Everything" but do not need a daemon process and can search arbitrary directories (not just those added to the index).

I think rather than adding "Everything" specifically as search backend, it would be better to provide some sort of API to add arbitrary search engines from the user config. Something like a callback function that the user can register with nvim-neo-tree that is called when a search is started and that can then use custom tools for searching. Or maybe something similar to `:h g:clipboard`.

**Comment by DasGandlaf** [comment]
@cseickel Yeah, I am on Windows. I do have `fd` installed, and it's in my path aswell. I don't know what might be causing this lag :/

@x3rAx That would definitely be a better way of handling this. But as cseickel said, it's not the search-tool that is slow. So I don't think having the ability to use another search tool is beneficial.
