### ISSUE TITLE
Need help on open file flow

### ISSUE THREAD

**Issue by Orgil** [nvim-neo-tree/neo-tree.nvim#730]
i want to open file with window picker if there are multiple window, just open if not. Tried to chain `open_with_window_picker` with `open_drop` but didn't work. Please advise how to achieve this flow.

**Comment by pysan3** [comment]
If I understand you correctly, you are trying to a) if only one buffer, open file automatically, and b) if there are multiple windows other than neo-tree, use [nvim-window-picker](https://github.com/s1n7ax/nvim-window-picker) to select which window to open, right?

This should be the default behavior without any specific configuration so could you show me your current configuration?

**Comment by Orgil** [comment]
@pysan3 i'm using alpha.nvim, `open_with_window_picker` not works if buffer is alpha.

**Comment by pysan3** [comment]
Hi @Orgil,

I have tried my best to reproduce your problem but unfortunately had no luck.

Could you post your config and a screen record to elaborate the problem?

> Tried to chain open_with_window_picker with open_drop but didn't work.

Besides, what do you mean by this?
At least I comprehended that as adding this code to neo-tree's codebase (since I don't think it's easy to achieve with custom commands. It is the easiest to use the `use_window_picker` function which is local to neo-tree codebase.)

With this modification, I have no issues opening with `drop_with_window_picker` even with alpha being one of the buffers.

```diff
Modified lua/neo-tree/sources/common/commands.lua
@@ -713,6 +713,11 @@ M.vsplit_with_window_picker = function(state, toggle_directory)
   open_with_cmd(state, "vsplit", toggle_directory, use_window_picker)
 end
 
+M.drop_with_window_picker = function(state, toggle_directory)
+  open_with_cmd(state, "drop", toggle_directory, use_window_picker)
+end
+
 M.show_help = function(state)
   help.show(state)
 end
```

**Comment by Orgil** [comment]
@pysan3 i'm not sure why mine config doesn't work. i mapped like `["o"] = "open_with_window_picker"`, so as soon as open neovim it brings `alpha.nvim` as startup buffer. So i called `:Neotree toggle` which brings neotree. From there toggling folder works find but to open file with `o` doesn't work. However `open_drop` works fine.

**Comment by nhat-vo** [comment]
@Orgil did you perhaps set `nvim-window-picker` to ignore the `alpha.nvim` buffer? You can see it in `filter_rules.bo.filetypes` of `nvim-window-picker`'s config.

**Comment by Orgil** [comment]
@nhat-vo that was it. i was misunderstanding that config and added alpha there previously. Thank you.
