### ISSUE TITLE
how to remove the fuzzy finder mapping?

### ISSUE THREAD

**Issue by mockdeep** [nvim-neo-tree/neo-tree.nvim#791]
Every time I jump into Neo Tree I end up using `/` to try to jump to a particular directory, but it instead does a filter. It's muscle memory at this point because normal vim windows do a search. Is there any way to disable the fuzzy finder and revert it to the default vim behavior?

**Comment by miversen33** [comment]
I've been thinking about fixing this (for myself) for a bit but haven't yet. Seems a good time to figure it out.

Does adding this to your neo-tree config work?
```lua
require("neo-tree").setup({
-- The rest of your configuration
    window = {
        mappings = {
            ['/'] = nil
        }
    }
})
```

**Comment by mockdeep** [comment]
@miversen33 hmm, no that doesn't seem to make a difference. I tried that and also tried nesting it under `filesystem` based on the readme, but neither had any effect. It still does the fuzzy find.

**Comment by miversen33** [comment]
Ok so quick digging in I have found a few things.

1) Removing [this line](https://github.com/nvim-neo-tree/neo-tree.nvim/blob/v2.x/lua/neo-tree/defaults.lua#L360) from defaults does indeed revert searching back to normal. This is good (though making changes to source is not preferred of course)

2) It doesn't appear that the config is doing anything to "force" the `fuzzy_find` mechanic. [Here](https://github.com/nvim-neo-tree/neo-tree.nvim/blob/v2.x/lua/neo-tree/setup/init.lua#L605-L609) is where the configuration is merged with the default configuration
The code is simply doing a deep merge preferring the user provided configuration over the default. So the reason my above example didn't work is because _technically_ you are unsetting `/`, which is then overridden by the defaults. 

You can _technically_ disable this behavior by just having an empty function there instead
```luarequire("neo-tree").setup({
-- The rest of your configuration
    window = {
        mappings = {
            ['/'] = function() end
        }
    }
})
```

And now fuzzy finding is gone. However, this does _not_ revert to normal vim search. **But**, if you can figure out how to start `search mode` from lua (I can't seem to figure it out, `:h search` is used for once you have a string to search for), you would just pop that into this function instead.

That said, I do wonder if this should be configurable _outside_ trickery like this. Fuzzy find is great, but IMO the ability to just search the current buffer is also great and it being displaced is not amazing.

@cseickel thoughts on how to work around this? Am I missing something in my shallow dive into this section of the code?

**Comment by cseickel** [comment]
Map it to `"none"`:
https://github.com/nvim-neo-tree/neo-tree.nvim/blob/aec592bb1f0cf67f7e1123053d1eb17700aa9ed4/doc/neo-tree.txt#L405-L421

**Comment by dimroc** [comment]
Building on the code suggestion below, is there an easy way to map `/` to `fzf` for real fuzzy search of files? I think it would be amazing and replace a big value prop of Telescope.

```lua
require("neo-tree").setup({
-- The rest of your configuration
    window = {
        mappings = {
            ['/'] = function() end
        }
    }
})
```

**Comment by nhat-vo** [comment]
@dimroc Not sure if this is what you need but you can do as follows. This creates a custom command `telescope` that invoke `Telescope find_files` and binds it to `/`.
```lua
require("neo-tree").setup({
	filesystem = {
		window = {
			mappings = {
				["/"] = "telescope",
			},
		},
		commands = {
			telescope = function()
				require("telescope.builtin").find_files({
					prompt_title = "Neotree",
				})
			end,
		},
	},
})
```

**Comment by dimroc** [comment]
Thanks @nhat-vo. I am hoping to keep the hierarchical folder view in the native Neotree. The telescope modal flattens the file path and has a worse visual for files imo

<img width="464" alt="image" src="https://user-images.githubusercontent.com/635121/230738644-c4e693a8-2ca4-40b8-8bf0-dde4e3c6ac7c.png">

<img width="873" alt="image" src="https://user-images.githubusercontent.com/635121/230738684-85987653-af77-49f3-b811-274f2b449749.png">

**Comment by nhat-vo** [comment]
Seems that you have created a new issue in #851, so as the original issue as been solved, I'll close this one.

**Comment by jondkinney** [comment]
This is working for me with AstroNVim v4

```lua
-- ~/.config/nvim/lua/plugins/neo-tree-overrides.lua
return {
  {
    "nvim-neo-tree/neo-tree.nvim",
    opts = function(_, opts)
      opts.window = vim.tbl_deep_extend("force", opts.window or {}, {
        auto_expand_width = true,
        mappings = {
          ["/"] = "noop", -- Disable the default mapping
        },
      })

      opts.filesystem = vim.tbl_deep_extend("force", opts.filesystem or {}, {
        filtered_items = {
          visible = true,
          never_show = {
            ".DS_Store",
            "thumbs.db",
            ".cache",
            ".git",
            ".github",
          },
        },
        follow_current_file = {
          enabled = true,
          leave_dirs_open = true,
        },
      })

      opts.group_empty_dirs = true

      return opts
    end,
    config = function(_, opts)
      require("neo-tree").setup(opts)

      -- Add a custom keymap for normal mode search in Neo-tree buffer
      vim.api.nvim_create_autocmd("FileType", {
        pattern = "neo-tree",
        callback = function() vim.api.nvim_buf_set_keymap(0, "n", "/", "/", { noremap = true, silent = true }) end,
      })
    end,
  },
}
```

**Comment by kevingposture** [comment]
I find that the next best solution with no additional config is to simply run `:/string`  + `Enter`.
