### ISSUE TITLE
Weird behaviour on buffer deletion

### ISSUE THREAD

**Issue by endlessqt** [nvim-neo-tree/neo-tree.nvim#821]
Hello, thank you for amazing plugin. I encountered some weird behaviour on :bdelete command when file-explorer is open.
 
### Current behaviour 
When neo-tree is open and i'm deleting currently selected buffer via :bdelete command, focus jumps to neo-tree and if i try to go to the next buffer via :bnext, neo-tree window just jumps to the right side of screen for no reason. 
Here's video demonstration of the behaviour. 

https://user-images.githubusercontent.com/67802059/226550758-185dd637-381a-4937-a958-1aa25a9a57ba.mov

### Expected behaviour
_If neo-tree is open, buffer deletion should focus the next buffer instead of focusing neo-tree._

When neo-tree is closed everything works correctly. On :bdelete next buffer is focused. 
Here's another demonstration of "normal behaviour" in my opinion.

https://user-images.githubusercontent.com/67802059/226551505-c30749b5-a45c-4806-b11a-22b38e6142b0.mov

### Here's my neo-tree config using lazy.nvim. 
I tried disabling __follow_current_file__ inside buffer and window options. The problem persists.
```lua
{
		"nvim-neo-tree/neo-tree.nvim",
		lazy = false,
		branch = "v2.x",
		dependencies = {
			"MunifTanjim/nui.nvim",
			"nvim-tree/nvim-web-devicons",
		},
		keys = {
			{ "<leader>bf", ":Neotree toggle left<CR>", silent = true },
		},
		opts = {
			window = {
				width = 30,
				position = "left",
			},
			filesystem = {
				use_libuv_file_watcher = true,
				follow_current_file = true,
				filtered_items = {
					visible = true,
					never_show = {
						".DS_Store",
					},
				},
			},
		},
		config = function(_, opts)
			vim.cmd([[ let g:neo_tree_remove_legacy_commands = 1 ]])
			require("neo-tree").setup(opts)
		end,
}
```

**Comment by nhat-vo** [comment]
@endlessqt Imo this is the behavior of `:bdelete` rather than neotree. `:bdelete` closes the window containing the buffer if there are at least 2 windows. That's why when you do `:bdelete` with a neotree pane, you got that behavior. 

You can use `vim-bbye` to modify this behavior. The plugin introduces additional commands to delete the buffer without closing the window, which seems to be what you want.

**Comment by endlessqt** [comment]
Thank you, so i'm closing the issue if its not a neo-tree problem.

**Comment by smartinellimarco** [comment]
@nhat-vo @endlessqt 
I wouldn't call it a problem, but I could not find a solution even by using vim-bbye or vim-sayonara.

Steps to reproduce (at least two buffers):
1. Delete a buffer (without deleting the window). The window now contains the previous buffer.
2. Switch focus to neotree.
3. Move to the next buffer (:bnext)
4. Neotree window now is at the right.

At that point the only way to move it back to the left is toggling it again.
In my case, I just configured the position to the right as default, where the mentioned above does not happens.

I noticed two more cases like this one:
- When using the netrw hijack option, neotree will toogle and create an empty buffer, but if you focus neotree and then do a :bnext, neotree closes.
- When on vsplit (two windows and neotree), if you focus neotree and do a :bnext, one vsplit window will close.

**Comment by cseickel** [comment]
@smartinellimarco This part just doesn't make sense:

> Switch focus to neotree.
Move to the next buffer (:bnext)

If you are using neo-tree as sidebar, and it sounds like that is what you are doing, you should **never** call `:bnext` from inside the neo-tree window. That will replace the neo-tree buffer with something else, which will then trigger window stealing prevention, that then causes wacky wacky behavior which is the result of a complicated interaction between your config and all of your other plugins which we do not know about.

Figuring out what causes neo-tree to reinstate itself in the wrong position is not really pertinent here, because the triggering situation is wrong and you just should not be doing that initentionally.

**Comment by smartinellimarco** [comment]
> @smartinellimarco This part just doesn't make sense:
> 
> > Switch focus to neotree.
> > Move to the next buffer (:bnext)
> 
> If you are using neo-tree as sidebar, and it sounds like that is what you are doing, you should **never** call `:bnext` from inside the neo-tree window. That will replace the neo-tree buffer with something else, which will then trigger window stealing prevention, that then causes the wacky behavior you described which is the result of a complicated interaction between your config and all of your other plugins which we do not know about.
> 
> Figuring out what causes neo-tree to reinstate itself in the wrong position is not really pertinent here, because the triggering situation is wrong and you just should not be doing that intentionally.

That behavior was produced with just neotree and one buffer closing plugin.
I was looking into making something like a regular editor with tabs (but in case of vim, buffers), with some robustness to weird key combinations or movements.
Its clear to me now that this is not what this tool is supposed to do.
I will try to implement a mapping to achieve this and paste it here. Perhaps switching focus from neotree to another window, before jumping to the next buffer. An autocmd might be enough.
Thanks for the reply.
Greetings!

**Comment by ralgar** [comment]
Has anybody figured out a workaround for this? @smartinellimarco @cseickel 

I use neo-tree as a permanent sidebar. I've had `:bprev` and `:bnext` bound to `<C-Left>` and `<C-Right>` in Normal mode for quick buffer switching for ages, since I was using regular Vim. However, if I happen to be in the neo-tree window by mistake (which happens daily), it reopens on the right side. It's a relatively minor inconvenience, but due to the frequency it does get rather annoying.

I've tested this on my old Vim config, with NerdTree, and it gracefully switches back to the main window without changing position.

**Comment by Wizermil** [comment]
After some research I finally figured a way to make `buffferline.nvim` work nicely with `neo-tree.nvim` and avoid this layout issue when switching or deleting buffers.

I used [`bufdelete.nvim`](https://github.com/famiu/bufdelete.nvim) for deleting the buffers and some custom lua code to switch between buffers.
I'm a huge nvim / lua beginner so don't hesitate to correct me if I'm wrong. I hope it will be helpful to other users 
```lua
left_mouse_command = function(bufnum)
  local lazy = require("bufferline.lazy")
  local ui = lazy.require("bufferline.ui")
  local windows = vim.fn.win_findbuf(bufnum)
  if windows[1] then
    vim.api.nvim_set_current_win(windows[1])
  end
  vim.schedule(function()
    vim.cmd(string.format("buffer %d", bufnum))
    ui.refresh()
  end)
end,
close_command = function(bufnum)
  require('bufdelete').bufdelete(bufnum, true)
end,
right_mouse_command = function(bufnum)
  require('bufdelete').bufdelete(bufnum, true)
end,
```

**Comment by hnpyn** [comment]
> After some research I finally figured a way to make `buffferline.nvim` work nicely with `neo-tree.nvim` and avoid this layout issue when switching or deleting buffers.
> 
> I used [`bufdelete.nvim`](https://github.com/famiu/bufdelete.nvim) for deleting the buffers and some custom lua code to switch between buffers. I'm a huge nvim / lua beginner so don't hesitate to correct me if I'm wrong. I hope it will be helpful to other users
> 
> ```lua
> left_mouse_command = function(bufnum)
>   local lazy = require("bufferline.lazy")
>   local ui = lazy.require("bufferline.ui")
>   local windows = vim.fn.win_findbuf(bufnum)
>   if windows[1] then
>     vim.api.nvim_set_current_win(windows[1])
>   end
>   vim.schedule(function()
>     vim.cmd(string.format("buffer %d", bufnum))
>     ui.refresh()
>   end)
> end,
> close_command = function(bufnum)
>   require('bufdelete').bufdelete(bufnum, true)
> end,
> right_mouse_command = function(bufnum)
>   require('bufdelete').bufdelete(bufnum, true)
> end,
> ```

this solved my problem, thank u
