### ISSUE TITLE
Add support for cwd_target = "none"

### ISSUE THREAD

**Issue by apazzolini** [nvim-neo-tree/neo-tree.nvim#835]
Would it be possible to add `"none"` as a `cwd_target` option? I use neo-tree in two ways:

1. Position = `sidebar`: When I change the root directory here, I would like the `cwd` in Neovim to update. This already works great with `cwd_target = "global"`.
2. Position = `current`: Here, I'm navigating for a nearby file. As I browse, I don't want the `cwd` to change at all.

I hope this might be as simple as returning `nil, nil` in `get_params_for_cwd` and some `if` checks in the two call sites, but I don't know if there are other reasons why this would be insufficient. Happy to put up a PR if that's all the work that's involved. Thank you!

**Comment by cseickel** [comment]
> Happy to put up a PR if that's all the work that's involved. Thank you!

Go for it! I honestly just didn't consider this combination of configuration and that's the only reason it's not supported. Right now there is just the global `bind_to_cwd` config option. It shouldn't be difficult to accept `"none"` as a choice for `cwd_target` and then not change the cwd.

**Comment by DorukAkinci** [comment]
A few days ago, I started using AstroNvim ( before I was trying Lunarvim and it came with neotree and it worked how I liked out of the box) and since then I have been struggling to solve this. I'm glad someone fixed it at the same time 🚀 

@apazzolini  ,  Should we set the configuration below to achieve this after the new version release? I suppose this will be the solution that I figured out from your initial message.
```
        filesystem = {
            bind_to_cwd = true,
            cwd_target = {
                sidebar = "global", -- sidebar is when position = left or right
                current = "none" -- current is when position = current
            },
        }
```
