### ISSUE TITLE
I need to know the `filetype`/`buftype` of the floating `y/n` window

### ISSUE THREAD

**Issue by nyngwang** [nvim-neo-tree/neo-tree.nvim#91]
As title. I use another plugin that will auto-resize a buffer/window if it's not in the excluded list. In this pic. the `Enter name for new ...` floating window got resized to a big one:

<img src="https://user-images.githubusercontent.com/24765272/150681918-1c5db659-db13-47ed-ac20-5996714879d7.png" width="700">

**Comment by nyngwang** [comment]
OK, I just resolve it myself with this settings in another plugin:

```
        excluded_filetypes = { 'fzf', 'neo-tree', 'packer', '' }, -- the last one resolved this issue.
```

I think it will be better to set a informative filetype for these little floating window, instead of a blank one.

**Comment by cseickel** [comment]
I'm not setting any filetype/buftype, but I really should and will. I think filetype because is easier to target with autocmds. This is a quick fix.

On a side note, why would you want a plugin that resizes windows on you? What windows are you resizing?

**Comment by nyngwang** [comment]
> On a side note, why would you want a plugin that resizes windows on you?

https://github.com/beauwilliams/focus.nvim

The reason is simple: the golden ratio works.

> What windows are you resizing?

All windows that under the same tab.

**Comment by cseickel** [comment]
That's actually quite interesting! I had tried to solve the same problem myself by making a tiling window manager with a large "main" window on the left and a stack of smaller windows on the right that I would move other windows into when I wanted to focus them. It worked but this is a better idea, resize in place rather than move.

That plugin should really ignore all floating windows by default. You might want to suggest that.

**Comment by cseickel** [comment]
This changed was merged to **main**, the filetype of popups is now `neo-tree-popup`. The issue should automatically close when it is released to **v1.x**.

**Comment by nyngwang** [comment]
Problem resolved. Thanks! :)
