### ISSUE TITLE
How do I prevent Neotree from filling the screen on buffer close?

### ISSUE THREAD

**Issue by ma-choo** [nvim-neo-tree/neo-tree.nvim#918]
When I close a buffer, the Neotree window (buffer?) fills the rest of the screen. However, I want my setup to behave like closing a tab in a traditional text editor. In this case, I want to focus on one of the other buffers instead of focusing Neotree. I'm not familiar with how windows/buffers/the like work in vim/nvim. How can I configure Neotree/nvim to maintain the same window/buffer composition when buffers are closed?

![image](https://user-images.githubusercontent.com/14033754/236637930-ad09511b-3393-4fc4-9978-ab9760aadd02.png)
![image](https://user-images.githubusercontent.com/14033754/236637932-21d83f5a-8f7a-4b91-8456-1a207d23bb14.png)

**Comment by StitiFatah** [comment]
I second this, it's frustrating me right now and don't even understand how it's working since it's not doing it every seingle time

**Comment by nhat-vo** [comment]
You can have a look at #821 for a discussion regarding this. TLDR, that is the expected behavior of vim's `:bdelete`, and you could solve this by using plugins such as vim-bbye or mini.bufremove. We do not plan to implement a fix built into Neo-tree, as this is not a bug but rather a difference in expectation.

I think it would be useful to mention this in the wiki. I will leave this open for now as a reminder to do it.

**Comment by nhat-vo** [comment]
For anyone that stumbles across this in the future, have a look at the wiki entry https://github.com/nvim-neo-tree/neo-tree.nvim/wiki/FAQ#bdelete-makes-the-tree-spans-the-whole-window-how-do-i-prevent-it
