### ISSUE TITLE
Netrw flashes when opening my cwd with nvim .

### ISSUE THREAD

**Issue by TLSingh1** [nvim-neo-tree/neo-tree.nvim#943]
Hi,

Thank you so much for the amazing plugin. Ive tried many file trees but this has been my favorite by far.

As the title suggests, netrw is flashing every time I open my cwd with nvim .

Altho it will almost immediately be displaced by neo-tree, and doesnt interrupt my workflow

Sorry for the noob question. Any guidance would be super appreciated!

**Comment by pysan3** [comment]
Neo-tree will hijack the netrw buffer if you set the `hijack_netrw_behavior` option.

This hijacking is done inside `require("neo-tree").setup` or on autocmd `BufEnter`, so if neither is called for a split second after you load neovim, yes, there would be netrw displayed in the buffer.
This will happen especially if you lazy load the plugin.

The easiest way I believe to _workaround_ this would be to simply disable netrw so that you will be seeing a blank buffer instead of netrw so that human eyes won't see anything weird.

```lua
-- put this somewhere in init.lua

vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1
vim.g.loaded_netrwSettings = 1
vim.g.loaded_netrwFileHandlers = 1
```

Besides, if you use `lazy.nvim`, you can disable it more easily.

https://github.com/folke/lazy.nvim#%EF%B8%8F-configuration

-> See config option of `performance.rtp.disabled_plugins`

**Comment by TLSingh1** [comment]
Thank you for the response, this works well tysm :pray:

**Comment by sghng** [comment]
@pysan3 I spend a lot of effort to find the solution in this issue. Maybe we should include it in neo tree documentations?
