### ISSUE TITLE
[Neo-tree ERROR] Preview cannot be used when positon = "current"

### ISSUE THREAD

**Issue by juxeii** [nvim-neo-tree/neo-tree.nvim#975]
Hi,

I am totally new to neo-tree and would like to see the preview window when navigating to a file.
I see no preview of any file, so I set the cursor to the file and hit "P".
But then the error
`[Neo-tree ERROR] Preview cannot be used when positon = "current"`
pops up. 
What does this mean and how can I see the preview window?

Thanks for you help.

**Comment by cseickel** [comment]
The preview feature was intended for use when Neotree is displayed in a sidebar or floating window, such as:
```
:Neotree float
:Neotree left
:Neotree right
```

The problem with trying to show a preview when "current" is the position is that it is not obvious what the size and position of the preview should be. That's why this feature is not available for that position.

**Comment by juxeii** [comment]
Thx!
`:Neotree left` did the trick for me.
